version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
        - mysqldb
  mysqldb:
    platform: linux/x86_64
    image: "mysql:8.0.31"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: db_researchers
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword
      MYSQL_ROOT_PASSWORD: ThePassword
