insert into revistas (id_revista, ano, mes, nombre) values (1, 2018, 10, 'Carroll and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (2, 1988, 7, 'Fisher Group');
insert into revistas (id_revista, ano, mes, nombre) values (3, 1998, 10, 'Deckow LLC');
insert into revistas (id_revista, ano, mes, nombre) values (4, 2012, 6, 'Metz-Oberbrunner');
insert into revistas (id_revista, ano, mes, nombre) values (5, 2014, 11, 'Walter-Rice');
insert into revistas (id_revista, ano, mes, nombre) values (6, 1930, 4, 'Lesch, Gutkowski and O''Reilly');
insert into revistas (id_revista, ano, mes, nombre) values (7, 2008, 10, 'Pollich-Brown');
insert into revistas (id_revista, ano, mes, nombre) values (8, 1971, 3, 'Harber-Denesik');
insert into revistas (id_revista, ano, mes, nombre) values (9, 2019, 3, 'Flatley-Stamm');
insert into revistas (id_revista, ano, mes, nombre) values (10, 2011, 4, 'Sauer, Legros and Russel');
insert into revistas (id_revista, ano, mes, nombre) values (11, 1950, 1, 'Franecki, Roob and Schmidt');
insert into revistas (id_revista, ano, mes, nombre) values (12, 2003, 2, 'Schulist and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (13, 1949, 5, 'Torp-Hilpert');
insert into revistas (id_revista, ano, mes, nombre) values (14, 1917, 12, 'Russel-Robel');
insert into revistas (id_revista, ano, mes, nombre) values (15, 1984, 9, 'Durgan LLC');
insert into revistas (id_revista, ano, mes, nombre) values (16, 1955, 2, 'Haag Inc');
insert into revistas (id_revista, ano, mes, nombre) values (17, 1944, 4, 'Rutherford-Cormier');
insert into revistas (id_revista, ano, mes, nombre) values (18, 1932, 6, 'Cruickshank Inc');
insert into revistas (id_revista, ano, mes, nombre) values (19, 1989, 11, 'Dach-Lehner');
insert into revistas (id_revista, ano, mes, nombre) values (20, 1919, 7, 'Rolfson-Spencer');
insert into revistas (id_revista, ano, mes, nombre) values (21, 1950, 1, 'Friesen, Robel and Zulauf');
insert into revistas (id_revista, ano, mes, nombre) values (22, 1943, 8, 'Nitzsche, Kessler and Champlin');
insert into revistas (id_revista, ano, mes, nombre) values (23, 2018, 12, 'Bahringer, Spinka and Ferry');
insert into revistas (id_revista, ano, mes, nombre) values (24, 1977, 11, 'Stehr Group');
insert into revistas (id_revista, ano, mes, nombre) values (25, 1982, 5, 'Donnelly, Daugherty and Schmeler');
insert into revistas (id_revista, ano, mes, nombre) values (26, 2012, 1, 'Torphy Group');
insert into revistas (id_revista, ano, mes, nombre) values (27, 1939, 11, 'Bode, Vandervort and Lindgren');
insert into revistas (id_revista, ano, mes, nombre) values (28, 2023, 10, 'Little Group');
insert into revistas (id_revista, ano, mes, nombre) values (29, 1989, 4, 'Turcotte-Hartmann');
insert into revistas (id_revista, ano, mes, nombre) values (30, 1995, 5, 'Heidenreich, Schneider and Little');
insert into revistas (id_revista, ano, mes, nombre) values (31, 2015, 6, 'Pollich, Boehm and Luettgen');
insert into revistas (id_revista, ano, mes, nombre) values (32, 1976, 6, 'Cremin Group');
insert into revistas (id_revista, ano, mes, nombre) values (33, 1934, 3, 'Howe-Becker');
insert into revistas (id_revista, ano, mes, nombre) values (34, 1968, 2, 'Ledner LLC');
insert into revistas (id_revista, ano, mes, nombre) values (35, 1951, 1, 'Greenfelder and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (36, 1972, 10, 'Stiedemann Inc');
insert into revistas (id_revista, ano, mes, nombre) values (37, 1997, 12, 'Bradtke LLC');
insert into revistas (id_revista, ano, mes, nombre) values (38, 1986, 2, 'Wintheiser Group');
insert into revistas (id_revista, ano, mes, nombre) values (39, 2005, 1, 'Kutch-Jaskolski');
insert into revistas (id_revista, ano, mes, nombre) values (40, 1972, 12, 'Cummings LLC');
insert into revistas (id_revista, ano, mes, nombre) values (41, 2009, 4, 'Ondricka, Bahringer and Kerluke');
insert into revistas (id_revista, ano, mes, nombre) values (42, 1927, 7, 'Smith, Jast and Leffler');
insert into revistas (id_revista, ano, mes, nombre) values (43, 1975, 4, 'Mayer Inc');
insert into revistas (id_revista, ano, mes, nombre) values (44, 1988, 3, 'Macejkovic, Medhurst and Howe');
insert into revistas (id_revista, ano, mes, nombre) values (45, 1998, 11, 'Bergnaum Group');
insert into revistas (id_revista, ano, mes, nombre) values (46, 1935, 9, 'Kuhic-Larson');
insert into revistas (id_revista, ano, mes, nombre) values (47, 1948, 1, 'Veum, Hayes and Heidenreich');
insert into revistas (id_revista, ano, mes, nombre) values (48, 2023, 1, 'Crist-Schoen');
insert into revistas (id_revista, ano, mes, nombre) values (49, 1929, 7, 'Bailey-Waelchi');
insert into revistas (id_revista, ano, mes, nombre) values (50, 1983, 10, 'Rau, Mann and Littel');
insert into revistas (id_revista, ano, mes, nombre) values (51, 1926, 1, 'Nicolas and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (52, 1941, 2, 'Sauer, Tillman and Lesch');
insert into revistas (id_revista, ano, mes, nombre) values (53, 1980, 3, 'Glover Inc');
insert into revistas (id_revista, ano, mes, nombre) values (54, 1952, 6, 'Stamm-Hansen');
insert into revistas (id_revista, ano, mes, nombre) values (55, 1918, 10, 'Okuneva Inc');
insert into revistas (id_revista, ano, mes, nombre) values (56, 2023, 5, 'Blick, Lang and Thiel');
insert into revistas (id_revista, ano, mes, nombre) values (57, 1976, 9, 'Kihn-Johnson');
insert into revistas (id_revista, ano, mes, nombre) values (58, 1924, 6, 'Jones Group');
insert into revistas (id_revista, ano, mes, nombre) values (59, 1929, 7, 'Greenholt Group');
insert into revistas (id_revista, ano, mes, nombre) values (60, 1918, 10, 'Price-McLaughlin');
insert into revistas (id_revista, ano, mes, nombre) values (61, 2016, 7, 'Predovic Inc');
insert into revistas (id_revista, ano, mes, nombre) values (62, 1973, 5, 'Haley Inc');
insert into revistas (id_revista, ano, mes, nombre) values (63, 1997, 4, 'Moore, Krajcik and Senger');
insert into revistas (id_revista, ano, mes, nombre) values (64, 1959, 3, 'Corwin Inc');
insert into revistas (id_revista, ano, mes, nombre) values (65, 2022, 6, 'Koepp Group');
insert into revistas (id_revista, ano, mes, nombre) values (66, 1975, 6, 'Pagac Inc');
insert into revistas (id_revista, ano, mes, nombre) values (67, 1928, 1, 'Rowe LLC');
insert into revistas (id_revista, ano, mes, nombre) values (68, 1982, 10, 'Blick-Thompson');
insert into revistas (id_revista, ano, mes, nombre) values (69, 1955, 5, 'Armstrong, Emard and Spinka');
insert into revistas (id_revista, ano, mes, nombre) values (70, 2006, 1, 'McDermott, Wehner and Labadie');
insert into revistas (id_revista, ano, mes, nombre) values (71, 1942, 8, 'Rippin Group');
insert into revistas (id_revista, ano, mes, nombre) values (72, 2012, 11, 'O''Conner, Buckridge and Hackett');
insert into revistas (id_revista, ano, mes, nombre) values (73, 2002, 1, 'Torp, Rohan and Kub');
insert into revistas (id_revista, ano, mes, nombre) values (74, 1983, 4, 'Hessel, Hilpert and Jast');
insert into revistas (id_revista, ano, mes, nombre) values (75, 2003, 8, 'Monahan-Bruen');
insert into revistas (id_revista, ano, mes, nombre) values (76, 1952, 1, 'Nicolas Inc');
insert into revistas (id_revista, ano, mes, nombre) values (77, 1997, 2, 'Emard-Buckridge');
insert into revistas (id_revista, ano, mes, nombre) values (78, 1962, 12, 'Schoen, Kozey and Kirlin');
insert into revistas (id_revista, ano, mes, nombre) values (79, 1984, 1, 'Beahan-Weissnat');
insert into revistas (id_revista, ano, mes, nombre) values (80, 1971, 12, 'Welch, Roob and Cronin');
insert into revistas (id_revista, ano, mes, nombre) values (81, 1951, 6, 'Johns Group');
insert into revistas (id_revista, ano, mes, nombre) values (82, 1994, 10, 'McKenzie-Corwin');
insert into revistas (id_revista, ano, mes, nombre) values (83, 1993, 4, 'Huels LLC');
insert into revistas (id_revista, ano, mes, nombre) values (84, 1999, 5, 'Rath-Fay');
insert into revistas (id_revista, ano, mes, nombre) values (85, 1992, 2, 'Johns Inc');
insert into revistas (id_revista, ano, mes, nombre) values (86, 1967, 12, 'Kuvalis, Zemlak and Borer');
insert into revistas (id_revista, ano, mes, nombre) values (87, 2018, 6, 'Schinner-Denesik');
insert into revistas (id_revista, ano, mes, nombre) values (88, 1986, 9, 'Nienow-Macejkovic');
insert into revistas (id_revista, ano, mes, nombre) values (89, 2005, 2, 'Roob, Crona and Brown');
insert into revistas (id_revista, ano, mes, nombre) values (90, 2020, 12, 'Glover Group');
insert into revistas (id_revista, ano, mes, nombre) values (91, 1943, 4, 'Hagenes LLC');
insert into revistas (id_revista, ano, mes, nombre) values (92, 1978, 9, 'Deckow, Okuneva and Koepp');
insert into revistas (id_revista, ano, mes, nombre) values (93, 1931, 7, 'Yundt-Rogahn');
insert into revistas (id_revista, ano, mes, nombre) values (94, 2002, 8, 'Koss Group');
insert into revistas (id_revista, ano, mes, nombre) values (95, 1975, 9, 'Feeney LLC');
insert into revistas (id_revista, ano, mes, nombre) values (96, 1937, 11, 'Swift-Herman');
insert into revistas (id_revista, ano, mes, nombre) values (97, 1975, 3, 'Parker, Turcotte and Romaguera');
insert into revistas (id_revista, ano, mes, nombre) values (98, 2020, 7, 'Ritchie-Conn');
insert into revistas (id_revista, ano, mes, nombre) values (99, 1962, 12, 'Dibbert, Okuneva and Balistreri');
insert into revistas (id_revista, ano, mes, nombre) values (100, 1914, 4, 'Schaden-Brekke');
insert into revistas (id_revista, ano, mes, nombre) values (101, 1956, 1, 'Hodkiewicz-Blick');
insert into revistas (id_revista, ano, mes, nombre) values (102, 1924, 9, 'Schiller Inc');
insert into revistas (id_revista, ano, mes, nombre) values (103, 2019, 7, 'Schmitt, Shields and Schaefer');
insert into revistas (id_revista, ano, mes, nombre) values (104, 1950, 7, 'Hauck, Becker and Hamill');
insert into revistas (id_revista, ano, mes, nombre) values (105, 1954, 8, 'Hettinger-Cormier');
insert into revistas (id_revista, ano, mes, nombre) values (106, 1988, 6, 'Herzog-Witting');
insert into revistas (id_revista, ano, mes, nombre) values (107, 1963, 10, 'Barton, Dickinson and Kshlerin');
insert into revistas (id_revista, ano, mes, nombre) values (108, 1927, 6, 'Shanahan, Smitham and Langosh');
insert into revistas (id_revista, ano, mes, nombre) values (109, 1953, 4, 'Terry, Kessler and Fay');
insert into revistas (id_revista, ano, mes, nombre) values (110, 1999, 1, 'Mante and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (111, 1973, 1, 'Flatley and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (112, 2017, 10, 'Walker Inc');
insert into revistas (id_revista, ano, mes, nombre) values (113, 2001, 3, 'Nikolaus LLC');
insert into revistas (id_revista, ano, mes, nombre) values (114, 1994, 12, 'Pagac, Hackett and Emmerich');
insert into revistas (id_revista, ano, mes, nombre) values (115, 1975, 8, 'Klein-Johnson');
insert into revistas (id_revista, ano, mes, nombre) values (116, 2012, 11, 'Funk Inc');
insert into revistas (id_revista, ano, mes, nombre) values (117, 1970, 7, 'Heaney LLC');
insert into revistas (id_revista, ano, mes, nombre) values (118, 2014, 3, 'Collier-Simonis');
insert into revistas (id_revista, ano, mes, nombre) values (119, 1965, 5, 'Rutherford Group');
insert into revistas (id_revista, ano, mes, nombre) values (120, 1998, 12, 'Wilderman, Rosenbaum and Hickle');
insert into revistas (id_revista, ano, mes, nombre) values (121, 2015, 1, 'Mertz Inc');
insert into revistas (id_revista, ano, mes, nombre) values (122, 2020, 7, 'Johnson-Koepp');
insert into revistas (id_revista, ano, mes, nombre) values (123, 1973, 12, 'Wisozk-Predovic');
insert into revistas (id_revista, ano, mes, nombre) values (124, 1965, 1, 'Rohan-Wyman');
insert into revistas (id_revista, ano, mes, nombre) values (125, 1972, 2, 'Harris LLC');
insert into revistas (id_revista, ano, mes, nombre) values (126, 1928, 10, 'Ullrich-Homenick');
insert into revistas (id_revista, ano, mes, nombre) values (127, 1996, 10, 'Bosco-Nicolas');
insert into revistas (id_revista, ano, mes, nombre) values (128, 1928, 4, 'Botsford-Dare');
insert into revistas (id_revista, ano, mes, nombre) values (129, 2023, 3, 'Powlowski Group');
insert into revistas (id_revista, ano, mes, nombre) values (130, 1925, 8, 'Douglas LLC');
insert into revistas (id_revista, ano, mes, nombre) values (131, 2006, 6, 'Altenwerth-Orn');
insert into revistas (id_revista, ano, mes, nombre) values (132, 1928, 12, 'Beer-Mertz');
insert into revistas (id_revista, ano, mes, nombre) values (133, 1938, 4, 'Jacobi LLC');
insert into revistas (id_revista, ano, mes, nombre) values (134, 2018, 9, 'Rogahn-Kilback');
insert into revistas (id_revista, ano, mes, nombre) values (135, 1977, 12, 'Tillman-Rodriguez');
insert into revistas (id_revista, ano, mes, nombre) values (136, 1959, 2, 'Beier, Wiza and Russel');
insert into revistas (id_revista, ano, mes, nombre) values (137, 2018, 8, 'Schmitt, Halvorson and Langworth');
insert into revistas (id_revista, ano, mes, nombre) values (138, 1946, 1, 'Prosacco, Strosin and Rodriguez');
insert into revistas (id_revista, ano, mes, nombre) values (139, 1933, 1, 'Schmidt-Langosh');
insert into revistas (id_revista, ano, mes, nombre) values (140, 1974, 5, 'Hansen, Fay and Doyle');
insert into revistas (id_revista, ano, mes, nombre) values (141, 1994, 2, 'Bogisich LLC');
insert into revistas (id_revista, ano, mes, nombre) values (142, 1949, 12, 'Spinka LLC');
insert into revistas (id_revista, ano, mes, nombre) values (143, 1964, 4, 'Mertz-Bergnaum');
insert into revistas (id_revista, ano, mes, nombre) values (144, 2006, 3, 'Roob-DuBuque');
insert into revistas (id_revista, ano, mes, nombre) values (145, 1978, 6, 'Braun-Kuvalis');
insert into revistas (id_revista, ano, mes, nombre) values (146, 1959, 6, 'Rau-Gibson');
insert into revistas (id_revista, ano, mes, nombre) values (147, 1947, 4, 'Lubowitz-Herman');
insert into revistas (id_revista, ano, mes, nombre) values (148, 1955, 9, 'Rodriguez-Champlin');
insert into revistas (id_revista, ano, mes, nombre) values (149, 1992, 4, 'Smith, Kub and Beahan');
insert into revistas (id_revista, ano, mes, nombre) values (150, 1929, 11, 'Funk, Ankunding and Jenkins');
insert into revistas (id_revista, ano, mes, nombre) values (151, 1978, 10, 'Osinski, Mills and Daniel');
insert into revistas (id_revista, ano, mes, nombre) values (152, 1968, 10, 'Schaefer and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (153, 1975, 11, 'Halvorson and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (154, 2000, 6, 'Wehner, Kutch and O''Reilly');
insert into revistas (id_revista, ano, mes, nombre) values (155, 1948, 6, 'Lemke, Murray and Konopelski');
insert into revistas (id_revista, ano, mes, nombre) values (156, 2012, 4, 'Herman, Koepp and Olson');
insert into revistas (id_revista, ano, mes, nombre) values (157, 2013, 8, 'Roob, Paucek and Davis');
insert into revistas (id_revista, ano, mes, nombre) values (158, 1979, 11, 'Mitchell and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (159, 1954, 11, 'Hilpert-Bradtke');
insert into revistas (id_revista, ano, mes, nombre) values (160, 2013, 2, 'Mueller-Wilderman');
insert into revistas (id_revista, ano, mes, nombre) values (161, 2011, 5, 'Emmerich, Grady and Prosacco');
insert into revistas (id_revista, ano, mes, nombre) values (162, 1935, 9, 'Mueller, Kiehn and Corkery');
insert into revistas (id_revista, ano, mes, nombre) values (163, 1962, 5, 'Hirthe Inc');
insert into revistas (id_revista, ano, mes, nombre) values (164, 1994, 2, 'Kertzmann-Buckridge');
insert into revistas (id_revista, ano, mes, nombre) values (165, 2023, 8, 'Hudson, Labadie and Dietrich');
insert into revistas (id_revista, ano, mes, nombre) values (166, 2011, 4, 'Doyle Group');
insert into revistas (id_revista, ano, mes, nombre) values (167, 1920, 4, 'Gorczany-Macejkovic');
insert into revistas (id_revista, ano, mes, nombre) values (168, 1931, 1, 'Wilkinson-Volkman');
insert into revistas (id_revista, ano, mes, nombre) values (169, 1916, 7, 'Lang Group');
insert into revistas (id_revista, ano, mes, nombre) values (170, 1960, 9, 'Kozey, Steuber and Kunde');
insert into revistas (id_revista, ano, mes, nombre) values (171, 2013, 1, 'Hansen Group');
insert into revistas (id_revista, ano, mes, nombre) values (172, 1999, 7, 'Leffler, Wiza and Torphy');
insert into revistas (id_revista, ano, mes, nombre) values (173, 1994, 7, 'Lockman, Bartoletti and Robel');
insert into revistas (id_revista, ano, mes, nombre) values (174, 1981, 2, 'Tremblay-Dibbert');
insert into revistas (id_revista, ano, mes, nombre) values (175, 2011, 9, 'Walter, Walsh and Lebsack');
insert into revistas (id_revista, ano, mes, nombre) values (176, 1940, 2, 'Terry, Ledner and Ruecker');
insert into revistas (id_revista, ano, mes, nombre) values (177, 1930, 4, 'Lind-Wuckert');
insert into revistas (id_revista, ano, mes, nombre) values (178, 1957, 2, 'McClure Inc');
insert into revistas (id_revista, ano, mes, nombre) values (179, 1939, 10, 'Botsford, Wuckert and Walker');
insert into revistas (id_revista, ano, mes, nombre) values (180, 1959, 4, 'Koch LLC');
insert into revistas (id_revista, ano, mes, nombre) values (181, 2022, 7, 'Cruickshank and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (182, 1927, 7, 'Kulas, Leannon and Dooley');
insert into revistas (id_revista, ano, mes, nombre) values (183, 1920, 7, 'Ebert, Orn and Weimann');
insert into revistas (id_revista, ano, mes, nombre) values (184, 2021, 7, 'Bergnaum, Kshlerin and Sauer');
insert into revistas (id_revista, ano, mes, nombre) values (185, 1936, 2, 'Satterfield Group');
insert into revistas (id_revista, ano, mes, nombre) values (186, 2022, 5, 'Kreiger-Boyle');
insert into revistas (id_revista, ano, mes, nombre) values (187, 1939, 10, 'Welch, Pollich and Auer');
insert into revistas (id_revista, ano, mes, nombre) values (188, 1995, 1, 'Romaguera, Prohaska and Paucek');
insert into revistas (id_revista, ano, mes, nombre) values (189, 1999, 10, 'Roberts, Koepp and Leannon');
insert into revistas (id_revista, ano, mes, nombre) values (190, 1980, 12, 'Beier-Trantow');
insert into revistas (id_revista, ano, mes, nombre) values (191, 2015, 4, 'Moore, Waelchi and Wiza');
insert into revistas (id_revista, ano, mes, nombre) values (192, 2000, 12, 'Howe, O''Kon and Hirthe');
insert into revistas (id_revista, ano, mes, nombre) values (193, 1958, 7, 'Sporer Inc');
insert into revistas (id_revista, ano, mes, nombre) values (194, 2007, 4, 'Gibson LLC');
insert into revistas (id_revista, ano, mes, nombre) values (195, 1944, 1, 'Marquardt-Hickle');
insert into revistas (id_revista, ano, mes, nombre) values (196, 1923, 7, 'Weissnat-Raynor');
insert into revistas (id_revista, ano, mes, nombre) values (197, 2017, 9, 'Graham-Wisoky');
insert into revistas (id_revista, ano, mes, nombre) values (198, 1939, 9, 'Kihn-Wehner');
insert into revistas (id_revista, ano, mes, nombre) values (199, 2003, 7, 'Abbott and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (200, 1971, 10, 'Crona-Hane');
insert into revistas (id_revista, ano, mes, nombre) values (201, 1979, 1, 'Swaniawski-Durgan');
insert into revistas (id_revista, ano, mes, nombre) values (202, 1982, 5, 'Marquardt-Heaney');
insert into revistas (id_revista, ano, mes, nombre) values (203, 2002, 12, 'Upton, Predovic and Herzog');
insert into revistas (id_revista, ano, mes, nombre) values (204, 1979, 7, 'Lakin, Medhurst and Lind');
insert into revistas (id_revista, ano, mes, nombre) values (205, 1967, 4, 'D''Amore and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (206, 2012, 11, 'Raynor Group');
insert into revistas (id_revista, ano, mes, nombre) values (207, 1951, 5, 'Borer, Senger and Kutch');
insert into revistas (id_revista, ano, mes, nombre) values (208, 1965, 12, 'Stark-Bartell');
insert into revistas (id_revista, ano, mes, nombre) values (209, 1940, 2, 'Kunde-Wolf');
insert into revistas (id_revista, ano, mes, nombre) values (210, 2004, 2, 'Moore, Cremin and Champlin');
insert into revistas (id_revista, ano, mes, nombre) values (211, 1986, 11, 'Wisozk and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (212, 2019, 12, 'Kutch-Wolff');
insert into revistas (id_revista, ano, mes, nombre) values (213, 2005, 11, 'Kuhn-Roberts');
insert into revistas (id_revista, ano, mes, nombre) values (214, 1988, 1, 'Marquardt and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (215, 1936, 3, 'Reinger-Renner');
insert into revistas (id_revista, ano, mes, nombre) values (216, 1957, 10, 'Hoppe-Abernathy');
insert into revistas (id_revista, ano, mes, nombre) values (217, 2016, 8, 'Runte-Lehner');
insert into revistas (id_revista, ano, mes, nombre) values (218, 1995, 4, 'Walter, Sauer and Kshlerin');
insert into revistas (id_revista, ano, mes, nombre) values (219, 1972, 9, 'Weber and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (220, 1989, 11, 'Champlin-Pfeffer');
insert into revistas (id_revista, ano, mes, nombre) values (221, 2013, 3, 'Lindgren-Robel');
insert into revistas (id_revista, ano, mes, nombre) values (222, 1926, 9, 'Weber and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (223, 1963, 1, 'Rodriguez, Walter and Walsh');
insert into revistas (id_revista, ano, mes, nombre) values (224, 1978, 2, 'Beier-Murphy');
insert into revistas (id_revista, ano, mes, nombre) values (225, 1987, 3, 'Price-Beier');
insert into revistas (id_revista, ano, mes, nombre) values (226, 2013, 4, 'Rau LLC');
insert into revistas (id_revista, ano, mes, nombre) values (227, 1988, 6, 'Fadel LLC');
insert into revistas (id_revista, ano, mes, nombre) values (228, 1964, 7, 'Halvorson-McDermott');
insert into revistas (id_revista, ano, mes, nombre) values (229, 2005, 3, 'Huel Inc');
insert into revistas (id_revista, ano, mes, nombre) values (230, 1933, 10, 'Frami-O''Reilly');
insert into revistas (id_revista, ano, mes, nombre) values (231, 1952, 7, 'Gleichner LLC');
insert into revistas (id_revista, ano, mes, nombre) values (232, 1984, 3, 'Satterfield, Heathcote and Kunde');
insert into revistas (id_revista, ano, mes, nombre) values (233, 2002, 4, 'Crona Inc');
insert into revistas (id_revista, ano, mes, nombre) values (234, 1941, 3, 'Rippin LLC');
insert into revistas (id_revista, ano, mes, nombre) values (235, 1992, 12, 'Robel Group');
insert into revistas (id_revista, ano, mes, nombre) values (236, 1936, 8, 'Rodriguez and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (237, 1920, 11, 'Strosin LLC');
insert into revistas (id_revista, ano, mes, nombre) values (238, 1914, 10, 'Berge, Smith and Tromp');
insert into revistas (id_revista, ano, mes, nombre) values (239, 1939, 4, 'Williamson, Monahan and Pfeffer');
insert into revistas (id_revista, ano, mes, nombre) values (240, 1977, 7, 'Ebert LLC');
insert into revistas (id_revista, ano, mes, nombre) values (241, 1972, 8, 'VonRueden and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (242, 2000, 9, 'Hand-Schultz');
insert into revistas (id_revista, ano, mes, nombre) values (243, 1946, 7, 'Satterfield, Schaden and Towne');
insert into revistas (id_revista, ano, mes, nombre) values (244, 2019, 9, 'Halvorson-Reinger');
insert into revistas (id_revista, ano, mes, nombre) values (245, 1936, 3, 'Bashirian, Barton and Dare');
insert into revistas (id_revista, ano, mes, nombre) values (246, 1939, 7, 'Beahan, Raynor and Padberg');
insert into revistas (id_revista, ano, mes, nombre) values (247, 1955, 7, 'Berge Group');
insert into revistas (id_revista, ano, mes, nombre) values (248, 1976, 10, 'Schuster-Senger');
insert into revistas (id_revista, ano, mes, nombre) values (249, 1946, 12, 'Leuschke-Jacobi');
insert into revistas (id_revista, ano, mes, nombre) values (250, 2008, 1, 'Schuppe, Murazik and Stracke');
insert into revistas (id_revista, ano, mes, nombre) values (251, 1922, 12, 'Marquardt-West');
insert into revistas (id_revista, ano, mes, nombre) values (252, 1937, 12, 'Runolfsson, Mosciski and Hoeger');
insert into revistas (id_revista, ano, mes, nombre) values (253, 1972, 2, 'Grimes Group');
insert into revistas (id_revista, ano, mes, nombre) values (254, 1970, 7, 'Wuckert, Nikolaus and Lowe');
insert into revistas (id_revista, ano, mes, nombre) values (255, 1939, 8, 'Heidenreich, Mueller and Bernhard');
insert into revistas (id_revista, ano, mes, nombre) values (256, 1968, 8, 'Greenfelder-Waters');
insert into revistas (id_revista, ano, mes, nombre) values (257, 1915, 12, 'Schowalter Group');
insert into revistas (id_revista, ano, mes, nombre) values (258, 1929, 10, 'Marvin, Schiller and Blick');
insert into revistas (id_revista, ano, mes, nombre) values (259, 1993, 1, 'Lehner LLC');
insert into revistas (id_revista, ano, mes, nombre) values (260, 1996, 12, 'Hills Inc');
insert into revistas (id_revista, ano, mes, nombre) values (261, 1940, 7, 'Upton Inc');
insert into revistas (id_revista, ano, mes, nombre) values (262, 1940, 9, 'Collier-Hegmann');
insert into revistas (id_revista, ano, mes, nombre) values (263, 1951, 10, 'Wuckert and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (264, 1919, 2, 'McGlynn-Sipes');
insert into revistas (id_revista, ano, mes, nombre) values (265, 2005, 1, 'Hermann, Kuhic and Wolf');
insert into revistas (id_revista, ano, mes, nombre) values (266, 1936, 12, 'Greenfelder-Corkery');
insert into revistas (id_revista, ano, mes, nombre) values (267, 2013, 2, 'Sauer-Mueller');
insert into revistas (id_revista, ano, mes, nombre) values (268, 1973, 9, 'Pacocha Inc');
insert into revistas (id_revista, ano, mes, nombre) values (269, 1950, 5, 'Stamm LLC');
insert into revistas (id_revista, ano, mes, nombre) values (270, 1973, 4, 'VonRueden Inc');
insert into revistas (id_revista, ano, mes, nombre) values (271, 2014, 4, 'Nader, Jacobs and Walsh');
insert into revistas (id_revista, ano, mes, nombre) values (272, 1929, 10, 'Funk and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (273, 2022, 10, 'Gerlach-Kutch');
insert into revistas (id_revista, ano, mes, nombre) values (274, 1969, 6, 'Jerde LLC');
insert into revistas (id_revista, ano, mes, nombre) values (275, 1996, 6, 'Harvey-Swift');
insert into revistas (id_revista, ano, mes, nombre) values (276, 2004, 2, 'Lemke, Hagenes and Hilpert');
insert into revistas (id_revista, ano, mes, nombre) values (277, 2012, 7, 'Harris LLC');
insert into revistas (id_revista, ano, mes, nombre) values (278, 1981, 1, 'Mayert-Smith');
insert into revistas (id_revista, ano, mes, nombre) values (279, 1967, 5, 'Hahn Group');
insert into revistas (id_revista, ano, mes, nombre) values (280, 1962, 7, 'Lindgren LLC');
insert into revistas (id_revista, ano, mes, nombre) values (281, 1979, 12, 'Graham, Ryan and Doyle');
insert into revistas (id_revista, ano, mes, nombre) values (282, 1992, 9, 'Konopelski, Boehm and Greenfelder');
insert into revistas (id_revista, ano, mes, nombre) values (283, 1946, 3, 'Mayert, Hackett and Emard');
insert into revistas (id_revista, ano, mes, nombre) values (284, 1994, 7, 'Osinski-Christiansen');
insert into revistas (id_revista, ano, mes, nombre) values (285, 1975, 7, 'Daniel, O''Conner and Nicolas');
insert into revistas (id_revista, ano, mes, nombre) values (286, 1946, 3, 'Sauer-Haag');
insert into revistas (id_revista, ano, mes, nombre) values (287, 2012, 4, 'Blanda-Crona');
insert into revistas (id_revista, ano, mes, nombre) values (288, 1933, 6, 'Lang LLC');
insert into revistas (id_revista, ano, mes, nombre) values (289, 2000, 6, 'Stehr LLC');
insert into revistas (id_revista, ano, mes, nombre) values (290, 1968, 1, 'Boehm-Purdy');
insert into revistas (id_revista, ano, mes, nombre) values (291, 1919, 12, 'MacGyver LLC');
insert into revistas (id_revista, ano, mes, nombre) values (292, 1998, 6, 'Moore Inc');
insert into revistas (id_revista, ano, mes, nombre) values (293, 2018, 12, 'Kerluke-Schimmel');
insert into revistas (id_revista, ano, mes, nombre) values (294, 1928, 3, 'Kirlin and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (295, 1950, 6, 'Johnson-Heidenreich');
insert into revistas (id_revista, ano, mes, nombre) values (296, 2005, 11, 'Cormier Inc');
insert into revistas (id_revista, ano, mes, nombre) values (297, 1969, 4, 'Fahey LLC');
insert into revistas (id_revista, ano, mes, nombre) values (298, 1931, 1, 'Howe, Hartmann and Boehm');
insert into revistas (id_revista, ano, mes, nombre) values (299, 1945, 6, 'O''Reilly-Von');
insert into revistas (id_revista, ano, mes, nombre) values (300, 1919, 3, 'Hackett LLC');
insert into revistas (id_revista, ano, mes, nombre) values (301, 1925, 4, 'Bradtke-Murray');
insert into revistas (id_revista, ano, mes, nombre) values (302, 2003, 8, 'Herzog-Cole');
insert into revistas (id_revista, ano, mes, nombre) values (303, 2008, 5, 'Zieme-Renner');
insert into revistas (id_revista, ano, mes, nombre) values (304, 1939, 10, 'Ziemann, Moore and Treutel');
insert into revistas (id_revista, ano, mes, nombre) values (305, 1985, 12, 'Auer LLC');
insert into revistas (id_revista, ano, mes, nombre) values (306, 2016, 5, 'Bauch-Botsford');
insert into revistas (id_revista, ano, mes, nombre) values (307, 2008, 5, 'Morar, Ferry and Kuvalis');
insert into revistas (id_revista, ano, mes, nombre) values (308, 1989, 2, 'Price LLC');
insert into revistas (id_revista, ano, mes, nombre) values (309, 2023, 7, 'Koch Group');
insert into revistas (id_revista, ano, mes, nombre) values (310, 2023, 3, 'Hodkiewicz and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (311, 1964, 4, 'Pagac LLC');
insert into revistas (id_revista, ano, mes, nombre) values (312, 1967, 5, 'Ernser-Sauer');
insert into revistas (id_revista, ano, mes, nombre) values (313, 1948, 7, 'Flatley, Kuvalis and Mayer');
insert into revistas (id_revista, ano, mes, nombre) values (314, 1957, 5, 'O''Connell LLC');
insert into revistas (id_revista, ano, mes, nombre) values (315, 1998, 4, 'Lockman, Mills and Runte');
insert into revistas (id_revista, ano, mes, nombre) values (316, 1920, 7, 'Boyle and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (317, 1930, 12, 'Quigley Group');
insert into revistas (id_revista, ano, mes, nombre) values (318, 2018, 4, 'Feeney Inc');
insert into revistas (id_revista, ano, mes, nombre) values (319, 2015, 6, 'Kuhn-Medhurst');
insert into revistas (id_revista, ano, mes, nombre) values (320, 1920, 12, 'Ruecker Inc');
insert into revistas (id_revista, ano, mes, nombre) values (321, 1916, 10, 'Wilkinson, Moen and Gaylord');
insert into revistas (id_revista, ano, mes, nombre) values (322, 1996, 7, 'Kassulke Inc');
insert into revistas (id_revista, ano, mes, nombre) values (323, 1926, 4, 'Wintheiser, Willms and Kuhic');
insert into revistas (id_revista, ano, mes, nombre) values (324, 1988, 5, 'Satterfield-Simonis');
insert into revistas (id_revista, ano, mes, nombre) values (325, 1938, 3, 'Donnelly-Dach');
insert into revistas (id_revista, ano, mes, nombre) values (326, 1932, 1, 'Rutherford-Ernser');
insert into revistas (id_revista, ano, mes, nombre) values (327, 1956, 10, 'Turner, Renner and Marvin');
insert into revistas (id_revista, ano, mes, nombre) values (328, 1938, 7, 'Corwin LLC');
insert into revistas (id_revista, ano, mes, nombre) values (329, 1920, 7, 'Denesik, Jacobs and Buckridge');
insert into revistas (id_revista, ano, mes, nombre) values (330, 1981, 9, 'Barton, Glover and Schiller');
insert into revistas (id_revista, ano, mes, nombre) values (331, 1927, 10, 'Schaefer, Runolfsdottir and Keebler');
insert into revistas (id_revista, ano, mes, nombre) values (332, 1937, 6, 'Strosin, Champlin and Mosciski');
insert into revistas (id_revista, ano, mes, nombre) values (333, 1996, 12, 'Hackett-Hudson');
insert into revistas (id_revista, ano, mes, nombre) values (334, 1966, 2, 'Crooks Group');
insert into revistas (id_revista, ano, mes, nombre) values (335, 1971, 2, 'Bailey-Davis');
insert into revistas (id_revista, ano, mes, nombre) values (336, 2007, 2, 'Morar, Wilkinson and Stokes');
insert into revistas (id_revista, ano, mes, nombre) values (337, 2001, 8, 'Kulas and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (338, 1973, 12, 'Harris-Jaskolski');
insert into revistas (id_revista, ano, mes, nombre) values (339, 2018, 12, 'Corwin LLC');
insert into revistas (id_revista, ano, mes, nombre) values (340, 2005, 7, 'Lesch, Strosin and Dare');
insert into revistas (id_revista, ano, mes, nombre) values (341, 1999, 12, 'Pollich, Gorczany and Blick');
insert into revistas (id_revista, ano, mes, nombre) values (342, 2009, 5, 'Homenick and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (343, 1969, 10, 'Buckridge Group');
insert into revistas (id_revista, ano, mes, nombre) values (344, 2003, 7, 'Herzog-Jones');
insert into revistas (id_revista, ano, mes, nombre) values (345, 1954, 4, 'Upton Inc');
insert into revistas (id_revista, ano, mes, nombre) values (346, 1994, 7, 'Adams, O''Connell and Fahey');
insert into revistas (id_revista, ano, mes, nombre) values (347, 1933, 7, 'Hahn, Adams and Renner');
insert into revistas (id_revista, ano, mes, nombre) values (348, 1977, 11, 'Frami Inc');
insert into revistas (id_revista, ano, mes, nombre) values (349, 2011, 3, 'Auer, Keebler and Adams');
insert into revistas (id_revista, ano, mes, nombre) values (350, 1922, 8, 'Kirlin-Jerde');
insert into revistas (id_revista, ano, mes, nombre) values (351, 1962, 6, 'Fay-Effertz');
insert into revistas (id_revista, ano, mes, nombre) values (352, 1972, 10, 'Dicki, Olson and Dicki');
insert into revistas (id_revista, ano, mes, nombre) values (353, 1983, 4, 'Kuhic-Erdman');
insert into revistas (id_revista, ano, mes, nombre) values (354, 1964, 7, 'Morar, Douglas and D''Amore');
insert into revistas (id_revista, ano, mes, nombre) values (355, 1917, 4, 'Jones-Strosin');
insert into revistas (id_revista, ano, mes, nombre) values (356, 1994, 7, 'Boyle, Denesik and Lesch');
insert into revistas (id_revista, ano, mes, nombre) values (357, 1981, 7, 'Daniel-Huels');
insert into revistas (id_revista, ano, mes, nombre) values (358, 1927, 4, 'Gleichner-Greenholt');
insert into revistas (id_revista, ano, mes, nombre) values (359, 2001, 7, 'Kunde Group');
insert into revistas (id_revista, ano, mes, nombre) values (360, 1973, 9, 'Wilderman-Hand');
insert into revistas (id_revista, ano, mes, nombre) values (361, 1929, 7, 'Oberbrunner Group');
insert into revistas (id_revista, ano, mes, nombre) values (362, 1917, 8, 'Gibson Inc');
insert into revistas (id_revista, ano, mes, nombre) values (363, 2019, 9, 'Hodkiewicz-Dach');
insert into revistas (id_revista, ano, mes, nombre) values (364, 2019, 11, 'Little LLC');
insert into revistas (id_revista, ano, mes, nombre) values (365, 1999, 1, 'Stehr, Kuphal and Gleason');
insert into revistas (id_revista, ano, mes, nombre) values (366, 1941, 12, 'Rolfson-Fisher');
insert into revistas (id_revista, ano, mes, nombre) values (367, 2002, 12, 'Bogisich LLC');
insert into revistas (id_revista, ano, mes, nombre) values (368, 1920, 6, 'Boyle LLC');
insert into revistas (id_revista, ano, mes, nombre) values (369, 1954, 12, 'Weimann and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (370, 1991, 10, 'Kunde-Wisozk');
insert into revistas (id_revista, ano, mes, nombre) values (371, 1974, 5, 'Spinka, Auer and Abernathy');
insert into revistas (id_revista, ano, mes, nombre) values (372, 2012, 11, 'Johnston-Hahn');
insert into revistas (id_revista, ano, mes, nombre) values (373, 1992, 6, 'Dooley-Rutherford');
insert into revistas (id_revista, ano, mes, nombre) values (374, 1930, 4, 'Crist-Purdy');
insert into revistas (id_revista, ano, mes, nombre) values (375, 2000, 12, 'Little LLC');
insert into revistas (id_revista, ano, mes, nombre) values (376, 1945, 8, 'Mueller LLC');
insert into revistas (id_revista, ano, mes, nombre) values (377, 1969, 11, 'Beatty-Pfeffer');
insert into revistas (id_revista, ano, mes, nombre) values (378, 1924, 12, 'Schaden, Runolfsdottir and Kunze');
insert into revistas (id_revista, ano, mes, nombre) values (379, 1981, 12, 'Wisoky, Hahn and Rutherford');
insert into revistas (id_revista, ano, mes, nombre) values (380, 2019, 12, 'D''Amore, Wisoky and Langworth');
insert into revistas (id_revista, ano, mes, nombre) values (381, 1931, 3, 'Cummings, Marquardt and Schumm');
insert into revistas (id_revista, ano, mes, nombre) values (382, 1962, 9, 'Dietrich Inc');
insert into revistas (id_revista, ano, mes, nombre) values (383, 1988, 4, 'Kuvalis-Kuhn');
insert into revistas (id_revista, ano, mes, nombre) values (384, 1971, 3, 'Kihn, Bartell and Little');
insert into revistas (id_revista, ano, mes, nombre) values (385, 1988, 8, 'Conroy, Wolf and Sporer');
insert into revistas (id_revista, ano, mes, nombre) values (386, 2000, 12, 'Hettinger Inc');
insert into revistas (id_revista, ano, mes, nombre) values (387, 1992, 11, 'Lakin Inc');
insert into revistas (id_revista, ano, mes, nombre) values (388, 1969, 7, 'Rolfson, Langworth and Kshlerin');
insert into revistas (id_revista, ano, mes, nombre) values (389, 2005, 11, 'Schuster-Baumbach');
insert into revistas (id_revista, ano, mes, nombre) values (390, 1924, 5, 'Brekke, Hermiston and Yundt');
insert into revistas (id_revista, ano, mes, nombre) values (391, 1927, 10, 'Osinski, Hickle and McLaughlin');
insert into revistas (id_revista, ano, mes, nombre) values (392, 1976, 10, 'Murray-D''Amore');
insert into revistas (id_revista, ano, mes, nombre) values (393, 2015, 3, 'Schmitt Group');
insert into revistas (id_revista, ano, mes, nombre) values (394, 1915, 8, 'Schmeler-Erdman');
insert into revistas (id_revista, ano, mes, nombre) values (395, 1970, 11, 'Larkin and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (396, 2018, 3, 'Kling-Stark');
insert into revistas (id_revista, ano, mes, nombre) values (397, 1996, 2, 'Walter-Armstrong');
insert into revistas (id_revista, ano, mes, nombre) values (398, 1943, 11, 'Jakubowski, Klocko and Quigley');
insert into revistas (id_revista, ano, mes, nombre) values (399, 1943, 5, 'Feeney, Bahringer and Moen');
insert into revistas (id_revista, ano, mes, nombre) values (400, 1924, 9, 'Leuschke, Blanda and Swift');
insert into revistas (id_revista, ano, mes, nombre) values (401, 1960, 2, 'Gerlach-Wunsch');
insert into revistas (id_revista, ano, mes, nombre) values (402, 1973, 4, 'Ward and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (403, 1972, 9, 'Muller-Kilback');
insert into revistas (id_revista, ano, mes, nombre) values (404, 1964, 7, 'Beier LLC');
insert into revistas (id_revista, ano, mes, nombre) values (405, 1927, 7, 'Maggio Group');
insert into revistas (id_revista, ano, mes, nombre) values (406, 1954, 10, 'Fritsch Group');
insert into revistas (id_revista, ano, mes, nombre) values (407, 2017, 1, 'Leannon-Rau');
insert into revistas (id_revista, ano, mes, nombre) values (408, 1938, 11, 'Bartoletti Group');
insert into revistas (id_revista, ano, mes, nombre) values (409, 1999, 9, 'Paucek LLC');
insert into revistas (id_revista, ano, mes, nombre) values (410, 1982, 7, 'Johnston-Schneider');
insert into revistas (id_revista, ano, mes, nombre) values (411, 1919, 1, 'Harvey-Glover');
insert into revistas (id_revista, ano, mes, nombre) values (412, 1975, 5, 'Considine, Schimmel and Larkin');
insert into revistas (id_revista, ano, mes, nombre) values (413, 2001, 6, 'Nikolaus Inc');
insert into revistas (id_revista, ano, mes, nombre) values (414, 1963, 10, 'Wiza LLC');
insert into revistas (id_revista, ano, mes, nombre) values (415, 2015, 11, 'Heathcote Inc');
insert into revistas (id_revista, ano, mes, nombre) values (416, 1993, 9, 'Hickle, Cormier and Wiegand');
insert into revistas (id_revista, ano, mes, nombre) values (417, 2013, 6, 'Wiza, Bartell and Emmerich');
insert into revistas (id_revista, ano, mes, nombre) values (418, 1923, 6, 'Emmerich Inc');
insert into revistas (id_revista, ano, mes, nombre) values (419, 1915, 8, 'Crist-Borer');
insert into revistas (id_revista, ano, mes, nombre) values (420, 1929, 12, 'Marquardt Inc');
insert into revistas (id_revista, ano, mes, nombre) values (421, 1924, 2, 'Morissette, Streich and Fisher');
insert into revistas (id_revista, ano, mes, nombre) values (422, 1948, 5, 'Jacobi, Medhurst and Bogan');
insert into revistas (id_revista, ano, mes, nombre) values (423, 1940, 8, 'Wilkinson and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (424, 2023, 5, 'Ferry LLC');
insert into revistas (id_revista, ano, mes, nombre) values (425, 1993, 5, 'McDermott Inc');
insert into revistas (id_revista, ano, mes, nombre) values (426, 1972, 12, 'Aufderhar-Robel');
insert into revistas (id_revista, ano, mes, nombre) values (427, 2001, 9, 'Gorczany Inc');
insert into revistas (id_revista, ano, mes, nombre) values (428, 1943, 11, 'Auer-Bechtelar');
insert into revistas (id_revista, ano, mes, nombre) values (429, 1994, 4, 'Ortiz-Stanton');
insert into revistas (id_revista, ano, mes, nombre) values (430, 2011, 8, 'Strosin Group');
insert into revistas (id_revista, ano, mes, nombre) values (431, 2008, 1, 'Gerhold Inc');
insert into revistas (id_revista, ano, mes, nombre) values (432, 2022, 3, 'Schroeder-Schuster');
insert into revistas (id_revista, ano, mes, nombre) values (433, 1938, 8, 'Emard-Hamill');
insert into revistas (id_revista, ano, mes, nombre) values (434, 1943, 4, 'Daniel, McGlynn and Morar');
insert into revistas (id_revista, ano, mes, nombre) values (435, 2020, 2, 'Rempel-Hauck');
insert into revistas (id_revista, ano, mes, nombre) values (436, 1945, 7, 'Renner and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (437, 2016, 10, 'Okuneva LLC');
insert into revistas (id_revista, ano, mes, nombre) values (438, 1915, 11, 'Schuppe-Champlin');
insert into revistas (id_revista, ano, mes, nombre) values (439, 1973, 12, 'Mante-Waters');
insert into revistas (id_revista, ano, mes, nombre) values (440, 1956, 9, 'Brakus-Heaney');
insert into revistas (id_revista, ano, mes, nombre) values (441, 2023, 5, 'Fritsch and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (442, 1958, 5, 'Lubowitz, Muller and Lang');
insert into revistas (id_revista, ano, mes, nombre) values (443, 1958, 12, 'Wunsch, King and Green');
insert into revistas (id_revista, ano, mes, nombre) values (444, 1927, 1, 'Watsica, Johnson and Gislason');
insert into revistas (id_revista, ano, mes, nombre) values (445, 2002, 5, 'McDermott, Kuphal and Morissette');
insert into revistas (id_revista, ano, mes, nombre) values (446, 1982, 12, 'Marvin Inc');
insert into revistas (id_revista, ano, mes, nombre) values (447, 1941, 9, 'Ondricka Group');
insert into revistas (id_revista, ano, mes, nombre) values (448, 2008, 4, 'Little, Kunde and Farrell');
insert into revistas (id_revista, ano, mes, nombre) values (449, 2002, 9, 'McLaughlin Inc');
insert into revistas (id_revista, ano, mes, nombre) values (450, 2009, 5, 'Ward Inc');
insert into revistas (id_revista, ano, mes, nombre) values (451, 1952, 8, 'Weissnat-Tillman');
insert into revistas (id_revista, ano, mes, nombre) values (452, 1961, 4, 'Hilpert, Howe and Mosciski');
insert into revistas (id_revista, ano, mes, nombre) values (453, 1978, 2, 'Windler Inc');
insert into revistas (id_revista, ano, mes, nombre) values (454, 1974, 12, 'Skiles Group');
insert into revistas (id_revista, ano, mes, nombre) values (455, 1998, 3, 'Bruen Inc');
insert into revistas (id_revista, ano, mes, nombre) values (456, 2012, 6, 'Kilback, Bergnaum and Runolfsson');
insert into revistas (id_revista, ano, mes, nombre) values (457, 1923, 8, 'Borer, Ortiz and Botsford');
insert into revistas (id_revista, ano, mes, nombre) values (458, 1994, 2, 'Hansen Inc');
insert into revistas (id_revista, ano, mes, nombre) values (459, 2013, 2, 'Jones and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (460, 2002, 3, 'Kreiger, Kunde and Tillman');
insert into revistas (id_revista, ano, mes, nombre) values (461, 2004, 5, 'VonRueden-Weimann');
insert into revistas (id_revista, ano, mes, nombre) values (462, 1968, 6, 'Kovacek, Erdman and Bernier');
insert into revistas (id_revista, ano, mes, nombre) values (463, 1964, 2, 'Nicolas Inc');
insert into revistas (id_revista, ano, mes, nombre) values (464, 1998, 5, 'Powlowski LLC');
insert into revistas (id_revista, ano, mes, nombre) values (465, 2015, 8, 'Hilpert, Friesen and Swaniawski');
insert into revistas (id_revista, ano, mes, nombre) values (466, 1999, 11, 'Frami, Mante and Heaney');
insert into revistas (id_revista, ano, mes, nombre) values (467, 1927, 10, 'Goyette, Will and Hermiston');
insert into revistas (id_revista, ano, mes, nombre) values (468, 1954, 4, 'Abernathy, Mayer and Rohan');
insert into revistas (id_revista, ano, mes, nombre) values (469, 1935, 1, 'Champlin, Marvin and Metz');
insert into revistas (id_revista, ano, mes, nombre) values (470, 1992, 9, 'Jacobi LLC');
insert into revistas (id_revista, ano, mes, nombre) values (471, 1990, 7, 'Daniel Inc');
insert into revistas (id_revista, ano, mes, nombre) values (472, 2010, 3, 'Satterfield Group');
insert into revistas (id_revista, ano, mes, nombre) values (473, 1944, 10, 'Hintz and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (474, 1960, 3, 'Hane and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (475, 1930, 10, 'Prosacco LLC');
insert into revistas (id_revista, ano, mes, nombre) values (476, 2015, 6, 'McDermott, Douglas and Hermiston');
insert into revistas (id_revista, ano, mes, nombre) values (477, 1925, 12, 'Raynor-Pacocha');
insert into revistas (id_revista, ano, mes, nombre) values (478, 1990, 7, 'Feeney, Metz and Terry');
insert into revistas (id_revista, ano, mes, nombre) values (479, 2003, 12, 'Lubowitz LLC');
insert into revistas (id_revista, ano, mes, nombre) values (480, 2016, 12, 'Torp LLC');
insert into revistas (id_revista, ano, mes, nombre) values (481, 1988, 1, 'Gerlach Group');
insert into revistas (id_revista, ano, mes, nombre) values (482, 1933, 10, 'Greenholt-Yundt');
insert into revistas (id_revista, ano, mes, nombre) values (483, 1937, 10, 'Howe-Dickens');
insert into revistas (id_revista, ano, mes, nombre) values (484, 1918, 9, 'Renner and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (485, 2007, 12, 'Wisozk and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (486, 2001, 8, 'Gusikowski and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (487, 1943, 11, 'Nolan, Corkery and Kuhlman');
insert into revistas (id_revista, ano, mes, nombre) values (488, 2011, 4, 'O''Reilly, Bauch and Zieme');
insert into revistas (id_revista, ano, mes, nombre) values (489, 1970, 8, 'Gusikowski, Mertz and Cassin');
insert into revistas (id_revista, ano, mes, nombre) values (490, 2020, 2, 'Gusikowski, Heidenreich and Hermann');
insert into revistas (id_revista, ano, mes, nombre) values (491, 2015, 10, 'Runolfsdottir, Walker and Metz');
insert into revistas (id_revista, ano, mes, nombre) values (492, 1964, 11, 'Marquardt-Zboncak');
insert into revistas (id_revista, ano, mes, nombre) values (493, 1934, 2, 'Mosciski and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (494, 1980, 2, 'Walker Group');
insert into revistas (id_revista, ano, mes, nombre) values (495, 1942, 4, 'Koch, Leffler and Klocko');
insert into revistas (id_revista, ano, mes, nombre) values (496, 1987, 3, 'Johnson, Barrows and Aufderhar');
insert into revistas (id_revista, ano, mes, nombre) values (497, 1986, 7, 'Mertz, Kutch and Greenfelder');
insert into revistas (id_revista, ano, mes, nombre) values (498, 1925, 1, 'Goldner-Balistreri');
insert into revistas (id_revista, ano, mes, nombre) values (499, 1914, 3, 'McCullough-Lindgren');
insert into revistas (id_revista, ano, mes, nombre) values (500, 1920, 3, 'Hermann, Parisian and Wisoky');
insert into revistas (id_revista, ano, mes, nombre) values (501, 2002, 9, 'Kutch-Bauch');
insert into revistas (id_revista, ano, mes, nombre) values (502, 2012, 3, 'Goldner Group');
insert into revistas (id_revista, ano, mes, nombre) values (503, 1948, 9, 'Murphy and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (504, 1935, 6, 'Senger, Hayes and Durgan');
insert into revistas (id_revista, ano, mes, nombre) values (505, 1951, 6, 'Lindgren Group');
insert into revistas (id_revista, ano, mes, nombre) values (506, 1941, 10, 'Kertzmann LLC');
insert into revistas (id_revista, ano, mes, nombre) values (507, 1931, 11, 'Cole-Witting');
insert into revistas (id_revista, ano, mes, nombre) values (508, 1963, 7, 'Goyette, Hansen and Lang');
insert into revistas (id_revista, ano, mes, nombre) values (509, 1967, 3, 'Orn-Skiles');
insert into revistas (id_revista, ano, mes, nombre) values (510, 2014, 7, 'Herzog LLC');
insert into revistas (id_revista, ano, mes, nombre) values (511, 1927, 4, 'Tremblay Inc');
insert into revistas (id_revista, ano, mes, nombre) values (512, 1935, 7, 'Johns-Keeling');
insert into revistas (id_revista, ano, mes, nombre) values (513, 2018, 2, 'Harvey-Beatty');
insert into revistas (id_revista, ano, mes, nombre) values (514, 1954, 2, 'West-Robel');
insert into revistas (id_revista, ano, mes, nombre) values (515, 2009, 9, 'Mohr-Aufderhar');
insert into revistas (id_revista, ano, mes, nombre) values (516, 2020, 10, 'Mohr, Huels and Johnson');
insert into revistas (id_revista, ano, mes, nombre) values (517, 1967, 6, 'Graham-Fay');
insert into revistas (id_revista, ano, mes, nombre) values (518, 1926, 10, 'Hilpert, Leffler and Turcotte');
insert into revistas (id_revista, ano, mes, nombre) values (519, 2023, 8, 'Prohaska Group');
insert into revistas (id_revista, ano, mes, nombre) values (520, 1940, 2, 'Armstrong, DuBuque and Powlowski');
insert into revistas (id_revista, ano, mes, nombre) values (521, 1989, 3, 'Olson and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (522, 1985, 2, 'Hirthe, Stiedemann and Boyer');
insert into revistas (id_revista, ano, mes, nombre) values (523, 1984, 5, 'Parker-Schimmel');
insert into revistas (id_revista, ano, mes, nombre) values (524, 1968, 12, 'Schamberger, Shields and Gislason');
insert into revistas (id_revista, ano, mes, nombre) values (525, 2022, 5, 'Murray-Will');
insert into revistas (id_revista, ano, mes, nombre) values (526, 2015, 5, 'Koch and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (527, 1917, 9, 'Friesen-Harris');
insert into revistas (id_revista, ano, mes, nombre) values (528, 2017, 4, 'Dach, Wiegand and McGlynn');
insert into revistas (id_revista, ano, mes, nombre) values (529, 1942, 12, 'Quitzon, Wisozk and Lehner');
insert into revistas (id_revista, ano, mes, nombre) values (530, 2006, 10, 'Yost and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (531, 1955, 8, 'Hammes, Kunze and Keebler');
insert into revistas (id_revista, ano, mes, nombre) values (532, 1948, 10, 'Lueilwitz, Reynolds and Reinger');
insert into revistas (id_revista, ano, mes, nombre) values (533, 1975, 2, 'Spinka and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (534, 2007, 6, 'Kris, Leuschke and Berge');
insert into revistas (id_revista, ano, mes, nombre) values (535, 1963, 3, 'Block-Bahringer');
insert into revistas (id_revista, ano, mes, nombre) values (536, 1917, 4, 'Mraz, Hermiston and Windler');
insert into revistas (id_revista, ano, mes, nombre) values (537, 2020, 7, 'Hagenes, Jacobson and Kerluke');
insert into revistas (id_revista, ano, mes, nombre) values (538, 1975, 7, 'Osinski-Kuhn');
insert into revistas (id_revista, ano, mes, nombre) values (539, 1924, 11, 'Schowalter, Prosacco and Buckridge');
insert into revistas (id_revista, ano, mes, nombre) values (540, 1922, 8, 'Olson LLC');
insert into revistas (id_revista, ano, mes, nombre) values (541, 1980, 11, 'Volkman, Hyatt and Spencer');
insert into revistas (id_revista, ano, mes, nombre) values (542, 1955, 9, 'Schoen, Fisher and Hartmann');
insert into revistas (id_revista, ano, mes, nombre) values (543, 2003, 3, 'Wunsch-Goodwin');
insert into revistas (id_revista, ano, mes, nombre) values (544, 1971, 5, 'Kunze, Kirlin and Gislason');
insert into revistas (id_revista, ano, mes, nombre) values (545, 1967, 7, 'Lebsack-Swaniawski');
insert into revistas (id_revista, ano, mes, nombre) values (546, 1959, 11, 'Crooks Inc');
insert into revistas (id_revista, ano, mes, nombre) values (547, 2005, 10, 'Kilback, Wiza and VonRueden');
insert into revistas (id_revista, ano, mes, nombre) values (548, 1964, 4, 'Jacobi and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (549, 1999, 9, 'Howell and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (550, 2015, 5, 'Bins, Maggio and Raynor');
insert into revistas (id_revista, ano, mes, nombre) values (551, 1953, 8, 'Ullrich, Price and Ondricka');
insert into revistas (id_revista, ano, mes, nombre) values (552, 1929, 7, 'Ritchie, Runolfsson and Mertz');
insert into revistas (id_revista, ano, mes, nombre) values (553, 1991, 1, 'Bailey-Nicolas');
insert into revistas (id_revista, ano, mes, nombre) values (554, 1987, 2, 'Grady Group');
insert into revistas (id_revista, ano, mes, nombre) values (555, 1995, 8, 'Greenfelder, Auer and Haag');
insert into revistas (id_revista, ano, mes, nombre) values (556, 1918, 8, 'Boyle, Rodriguez and Langosh');
insert into revistas (id_revista, ano, mes, nombre) values (557, 1963, 5, 'McClure, Bosco and Stanton');
insert into revistas (id_revista, ano, mes, nombre) values (558, 1921, 5, 'Collier, Becker and Wehner');
insert into revistas (id_revista, ano, mes, nombre) values (559, 1931, 10, 'Stoltenberg-Roob');
insert into revistas (id_revista, ano, mes, nombre) values (560, 1957, 11, 'Pfeffer-Boehm');
insert into revistas (id_revista, ano, mes, nombre) values (561, 1956, 12, 'Jenkins, Schmitt and Marquardt');
insert into revistas (id_revista, ano, mes, nombre) values (562, 1948, 2, 'Bogisich and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (563, 1989, 7, 'Zemlak Inc');
insert into revistas (id_revista, ano, mes, nombre) values (564, 1944, 10, 'Hane Inc');
insert into revistas (id_revista, ano, mes, nombre) values (565, 2017, 12, 'Hudson and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (566, 2021, 10, 'Bailey, Ortiz and Schuster');
insert into revistas (id_revista, ano, mes, nombre) values (567, 1965, 3, 'Collier, Erdman and Langosh');
insert into revistas (id_revista, ano, mes, nombre) values (568, 1985, 11, 'Langosh, Wunsch and Frami');
insert into revistas (id_revista, ano, mes, nombre) values (569, 1992, 3, 'O''Connell, Prosacco and Dibbert');
insert into revistas (id_revista, ano, mes, nombre) values (570, 1937, 10, 'Schulist-Buckridge');
insert into revistas (id_revista, ano, mes, nombre) values (571, 1940, 2, 'Keebler, Klein and Cremin');
insert into revistas (id_revista, ano, mes, nombre) values (572, 1968, 7, 'Kuvalis-Moore');
insert into revistas (id_revista, ano, mes, nombre) values (573, 1989, 8, 'Champlin-Stanton');
insert into revistas (id_revista, ano, mes, nombre) values (574, 2014, 3, 'Witting LLC');
insert into revistas (id_revista, ano, mes, nombre) values (575, 2013, 4, 'Schuster-Vandervort');
insert into revistas (id_revista, ano, mes, nombre) values (576, 1918, 6, 'Little Inc');
insert into revistas (id_revista, ano, mes, nombre) values (577, 2015, 4, 'Effertz-Rippin');
insert into revistas (id_revista, ano, mes, nombre) values (578, 1942, 5, 'Lang-Emard');
insert into revistas (id_revista, ano, mes, nombre) values (579, 1970, 2, 'O''Conner-Bruen');
insert into revistas (id_revista, ano, mes, nombre) values (580, 1951, 3, 'McLaughlin, O''Keefe and Dibbert');
insert into revistas (id_revista, ano, mes, nombre) values (581, 1990, 3, 'Kiehn and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (582, 1976, 5, 'Sipes LLC');
insert into revistas (id_revista, ano, mes, nombre) values (583, 2007, 6, 'Kutch-Boyer');
insert into revistas (id_revista, ano, mes, nombre) values (584, 2009, 7, 'Wuckert-Jacobi');
insert into revistas (id_revista, ano, mes, nombre) values (585, 2002, 4, 'Dickinson-Steuber');
insert into revistas (id_revista, ano, mes, nombre) values (586, 1933, 11, 'Christiansen-Breitenberg');
insert into revistas (id_revista, ano, mes, nombre) values (587, 1959, 4, 'Keebler-Hoeger');
insert into revistas (id_revista, ano, mes, nombre) values (588, 1938, 2, 'Auer, Feil and Yundt');
insert into revistas (id_revista, ano, mes, nombre) values (589, 1923, 7, 'Auer Inc');
insert into revistas (id_revista, ano, mes, nombre) values (590, 2011, 12, 'Aufderhar, Swaniawski and Terry');
insert into revistas (id_revista, ano, mes, nombre) values (591, 2002, 6, 'Spencer-Bartell');
insert into revistas (id_revista, ano, mes, nombre) values (592, 1969, 9, 'Bradtke-Mayer');
insert into revistas (id_revista, ano, mes, nombre) values (593, 1966, 7, 'Dooley, Stracke and Nienow');
insert into revistas (id_revista, ano, mes, nombre) values (594, 1946, 10, 'Frami, Jakubowski and Runolfsdottir');
insert into revistas (id_revista, ano, mes, nombre) values (595, 2011, 7, 'Cummings LLC');
insert into revistas (id_revista, ano, mes, nombre) values (596, 1958, 9, 'Little Group');
insert into revistas (id_revista, ano, mes, nombre) values (597, 1975, 1, 'Kuhn, Dooley and Boehm');
insert into revistas (id_revista, ano, mes, nombre) values (598, 1914, 9, 'Harvey, Gerlach and VonRueden');
insert into revistas (id_revista, ano, mes, nombre) values (599, 1961, 11, 'Jones-Adams');
insert into revistas (id_revista, ano, mes, nombre) values (600, 1940, 5, 'Wehner-Towne');
insert into revistas (id_revista, ano, mes, nombre) values (601, 2012, 11, 'Hickle-Watsica');
insert into revistas (id_revista, ano, mes, nombre) values (602, 1952, 4, 'O''Keefe LLC');
insert into revistas (id_revista, ano, mes, nombre) values (603, 1936, 5, 'Halvorson, Schroeder and Keeling');
insert into revistas (id_revista, ano, mes, nombre) values (604, 1962, 3, 'Cormier and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (605, 1978, 4, 'Crist-Spencer');
insert into revistas (id_revista, ano, mes, nombre) values (606, 1940, 2, 'Kuhn LLC');
insert into revistas (id_revista, ano, mes, nombre) values (607, 1979, 10, 'Cormier LLC');
insert into revistas (id_revista, ano, mes, nombre) values (608, 1934, 4, 'Grimes Inc');
insert into revistas (id_revista, ano, mes, nombre) values (609, 1965, 4, 'Gerlach LLC');
insert into revistas (id_revista, ano, mes, nombre) values (610, 1919, 12, 'Terry-Gislason');
insert into revistas (id_revista, ano, mes, nombre) values (611, 1978, 4, 'Mueller Inc');
insert into revistas (id_revista, ano, mes, nombre) values (612, 1966, 12, 'Kunde Inc');
insert into revistas (id_revista, ano, mes, nombre) values (613, 1952, 10, 'MacGyver-Mayert');
insert into revistas (id_revista, ano, mes, nombre) values (614, 1928, 11, 'Smith-Sipes');
insert into revistas (id_revista, ano, mes, nombre) values (615, 1997, 12, 'Littel Group');
insert into revistas (id_revista, ano, mes, nombre) values (616, 2009, 8, 'Gusikowski-Johns');
insert into revistas (id_revista, ano, mes, nombre) values (617, 1959, 6, 'Block and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (618, 2000, 7, 'Labadie and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (619, 1950, 8, 'Homenick and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (620, 2000, 11, 'Mueller-Robel');
insert into revistas (id_revista, ano, mes, nombre) values (621, 1950, 11, 'West Inc');
insert into revistas (id_revista, ano, mes, nombre) values (622, 1951, 10, 'Klocko, Thompson and Auer');
insert into revistas (id_revista, ano, mes, nombre) values (623, 1929, 7, 'Schuster LLC');
insert into revistas (id_revista, ano, mes, nombre) values (624, 1990, 10, 'Okuneva-Lockman');
insert into revistas (id_revista, ano, mes, nombre) values (625, 1922, 1, 'Collier-Franecki');
insert into revistas (id_revista, ano, mes, nombre) values (626, 1917, 5, 'Kuphal-Cruickshank');
insert into revistas (id_revista, ano, mes, nombre) values (627, 2005, 4, 'Bayer LLC');
insert into revistas (id_revista, ano, mes, nombre) values (628, 1999, 7, 'Bailey Group');
insert into revistas (id_revista, ano, mes, nombre) values (629, 1992, 9, 'Douglas LLC');
insert into revistas (id_revista, ano, mes, nombre) values (630, 1961, 12, 'Schaden, Torphy and Ward');
insert into revistas (id_revista, ano, mes, nombre) values (631, 1978, 11, 'Buckridge LLC');
insert into revistas (id_revista, ano, mes, nombre) values (632, 1950, 6, 'Gaylord, Hansen and Stark');
insert into revistas (id_revista, ano, mes, nombre) values (633, 1988, 9, 'Gleason-Johnston');
insert into revistas (id_revista, ano, mes, nombre) values (634, 2011, 8, 'Wolf Group');
insert into revistas (id_revista, ano, mes, nombre) values (635, 1986, 4, 'Huel-Maggio');
insert into revistas (id_revista, ano, mes, nombre) values (636, 1991, 4, 'Auer, Boyle and Doyle');
insert into revistas (id_revista, ano, mes, nombre) values (637, 1958, 7, 'Kunde-Grant');
insert into revistas (id_revista, ano, mes, nombre) values (638, 1950, 9, 'Olson and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (639, 2012, 12, 'Murphy-Rath');
insert into revistas (id_revista, ano, mes, nombre) values (640, 1951, 9, 'Wiegand, Herzog and Schmitt');
insert into revistas (id_revista, ano, mes, nombre) values (641, 1955, 3, 'Grimes-Lynch');
insert into revistas (id_revista, ano, mes, nombre) values (642, 1928, 10, 'Monahan Group');
insert into revistas (id_revista, ano, mes, nombre) values (643, 1988, 2, 'Berge-Stamm');
insert into revistas (id_revista, ano, mes, nombre) values (644, 1968, 8, 'Romaguera, Schneider and Considine');
insert into revistas (id_revista, ano, mes, nombre) values (645, 2006, 7, 'Runte-McCullough');
insert into revistas (id_revista, ano, mes, nombre) values (646, 1989, 10, 'Schowalter, Wolff and West');
insert into revistas (id_revista, ano, mes, nombre) values (647, 1940, 9, 'Barrows Group');
insert into revistas (id_revista, ano, mes, nombre) values (648, 2020, 2, 'Morar, Dare and Williamson');
insert into revistas (id_revista, ano, mes, nombre) values (649, 2019, 1, 'Thompson Inc');
insert into revistas (id_revista, ano, mes, nombre) values (650, 1914, 1, 'Witting-Collier');
insert into revistas (id_revista, ano, mes, nombre) values (651, 2022, 8, 'Marks-Murray');
insert into revistas (id_revista, ano, mes, nombre) values (652, 2002, 6, 'Von, Kris and Little');
insert into revistas (id_revista, ano, mes, nombre) values (653, 2022, 6, 'Thompson LLC');
insert into revistas (id_revista, ano, mes, nombre) values (654, 1951, 4, 'Johns Inc');
insert into revistas (id_revista, ano, mes, nombre) values (655, 1978, 2, 'Bartell-Zulauf');
insert into revistas (id_revista, ano, mes, nombre) values (656, 2005, 11, 'Schmitt Group');
insert into revistas (id_revista, ano, mes, nombre) values (657, 2003, 3, 'Hahn, Heathcote and Wiza');
insert into revistas (id_revista, ano, mes, nombre) values (658, 1978, 6, 'Yundt, Quigley and Leuschke');
insert into revistas (id_revista, ano, mes, nombre) values (659, 1971, 11, 'Lueilwitz-Wisozk');
insert into revistas (id_revista, ano, mes, nombre) values (660, 1956, 7, 'Kertzmann, Barrows and Collier');
insert into revistas (id_revista, ano, mes, nombre) values (661, 1977, 6, 'Feil LLC');
insert into revistas (id_revista, ano, mes, nombre) values (662, 1993, 10, 'Jerde, Champlin and Sporer');
insert into revistas (id_revista, ano, mes, nombre) values (663, 1996, 3, 'Thompson, DuBuque and Schmeler');
insert into revistas (id_revista, ano, mes, nombre) values (664, 1958, 11, 'Bogisich Inc');
insert into revistas (id_revista, ano, mes, nombre) values (665, 1932, 3, 'Welch and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (666, 2004, 8, 'Zieme-King');
insert into revistas (id_revista, ano, mes, nombre) values (667, 1936, 12, 'Morar, Mayer and Zieme');
insert into revistas (id_revista, ano, mes, nombre) values (668, 2004, 12, 'Abbott, Simonis and Waters');
insert into revistas (id_revista, ano, mes, nombre) values (669, 1976, 5, 'Watsica-Morar');
insert into revistas (id_revista, ano, mes, nombre) values (670, 1972, 8, 'Jaskolski-Cummerata');
insert into revistas (id_revista, ano, mes, nombre) values (671, 2020, 2, 'Weber-Jerde');
insert into revistas (id_revista, ano, mes, nombre) values (672, 1976, 7, 'Reichert-Connelly');
insert into revistas (id_revista, ano, mes, nombre) values (673, 2012, 8, 'Lind-Simonis');
insert into revistas (id_revista, ano, mes, nombre) values (674, 2000, 2, 'Jones, Larkin and Zboncak');
insert into revistas (id_revista, ano, mes, nombre) values (675, 1938, 12, 'Kreiger-Jakubowski');
insert into revistas (id_revista, ano, mes, nombre) values (676, 1979, 11, 'Reynolds-Spinka');
insert into revistas (id_revista, ano, mes, nombre) values (677, 1929, 5, 'Schamberger LLC');
insert into revistas (id_revista, ano, mes, nombre) values (678, 1915, 12, 'Morar-Hagenes');
insert into revistas (id_revista, ano, mes, nombre) values (679, 1962, 12, 'Murphy-Ortiz');
insert into revistas (id_revista, ano, mes, nombre) values (680, 1959, 5, 'Rath-Hills');
insert into revistas (id_revista, ano, mes, nombre) values (681, 1985, 10, 'Lowe-Prohaska');
insert into revistas (id_revista, ano, mes, nombre) values (682, 1918, 2, 'Boyer-Bruen');
insert into revistas (id_revista, ano, mes, nombre) values (683, 1995, 11, 'MacGyver-Koepp');
insert into revistas (id_revista, ano, mes, nombre) values (684, 1972, 5, 'Bashirian-Kling');
insert into revistas (id_revista, ano, mes, nombre) values (685, 2017, 6, 'Ebert-Graham');
insert into revistas (id_revista, ano, mes, nombre) values (686, 1963, 9, 'Ruecker-Paucek');
insert into revistas (id_revista, ano, mes, nombre) values (687, 1995, 11, 'Kreiger-Turner');
insert into revistas (id_revista, ano, mes, nombre) values (688, 1964, 9, 'Frami Inc');
insert into revistas (id_revista, ano, mes, nombre) values (689, 1991, 9, 'Cruickshank and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (690, 1973, 11, 'Rosenbaum-O''Connell');
insert into revistas (id_revista, ano, mes, nombre) values (691, 2000, 10, 'Schmeler-Jacobson');
insert into revistas (id_revista, ano, mes, nombre) values (692, 1976, 7, 'Schmidt-Rutherford');
insert into revistas (id_revista, ano, mes, nombre) values (693, 2013, 9, 'Welch-Schulist');
insert into revistas (id_revista, ano, mes, nombre) values (694, 1944, 8, 'Osinski and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (695, 1993, 6, 'Carter and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (696, 1953, 11, 'Schaden, Nikolaus and Marks');
insert into revistas (id_revista, ano, mes, nombre) values (697, 1940, 3, 'Rau Group');
insert into revistas (id_revista, ano, mes, nombre) values (698, 1949, 12, 'Cormier-Baumbach');
insert into revistas (id_revista, ano, mes, nombre) values (699, 1968, 2, 'Howe and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (700, 1969, 8, 'Gutkowski LLC');
insert into revistas (id_revista, ano, mes, nombre) values (701, 2017, 7, 'Kuvalis Inc');
insert into revistas (id_revista, ano, mes, nombre) values (702, 1971, 7, 'Lindgren Group');
insert into revistas (id_revista, ano, mes, nombre) values (703, 1987, 5, 'Kuhn-Jacobi');
insert into revistas (id_revista, ano, mes, nombre) values (704, 2004, 9, 'Vandervort-Littel');
insert into revistas (id_revista, ano, mes, nombre) values (705, 1988, 4, 'Morissette, Windler and Upton');
insert into revistas (id_revista, ano, mes, nombre) values (706, 1943, 6, 'Goldner, Daniel and Stehr');
insert into revistas (id_revista, ano, mes, nombre) values (707, 1972, 4, 'Turcotte-Ward');
insert into revistas (id_revista, ano, mes, nombre) values (708, 1945, 7, 'Bauch LLC');
insert into revistas (id_revista, ano, mes, nombre) values (709, 1955, 3, 'Wolff Group');
insert into revistas (id_revista, ano, mes, nombre) values (710, 1953, 3, 'Koss and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (711, 2022, 3, 'Hayes-Lubowitz');
insert into revistas (id_revista, ano, mes, nombre) values (712, 1985, 5, 'Kris Group');
insert into revistas (id_revista, ano, mes, nombre) values (713, 1942, 6, 'Quigley-Torphy');
insert into revistas (id_revista, ano, mes, nombre) values (714, 1943, 11, 'Kassulke, Huels and Simonis');
insert into revistas (id_revista, ano, mes, nombre) values (715, 1953, 9, 'Kautzer and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (716, 1987, 1, 'Kuhlman, Hane and Pollich');
insert into revistas (id_revista, ano, mes, nombre) values (717, 1987, 3, 'Ratke, Corwin and Hills');
insert into revistas (id_revista, ano, mes, nombre) values (718, 1940, 4, 'Paucek, Ritchie and Walsh');
insert into revistas (id_revista, ano, mes, nombre) values (719, 1976, 8, 'Konopelski-Cummerata');
insert into revistas (id_revista, ano, mes, nombre) values (720, 1967, 6, 'Wiegand LLC');
insert into revistas (id_revista, ano, mes, nombre) values (721, 1984, 9, 'McGlynn-Cummings');
insert into revistas (id_revista, ano, mes, nombre) values (722, 1994, 12, 'Pouros, Bradtke and Bashirian');
insert into revistas (id_revista, ano, mes, nombre) values (723, 1930, 11, 'Keeling-Considine');
insert into revistas (id_revista, ano, mes, nombre) values (724, 1955, 10, 'Kuhn, Hermann and Predovic');
insert into revistas (id_revista, ano, mes, nombre) values (725, 1968, 7, 'Medhurst-Daniel');
insert into revistas (id_revista, ano, mes, nombre) values (726, 1958, 3, 'Conn-Block');
insert into revistas (id_revista, ano, mes, nombre) values (727, 1982, 2, 'Murazik-Murphy');
insert into revistas (id_revista, ano, mes, nombre) values (728, 1996, 8, 'Harber LLC');
insert into revistas (id_revista, ano, mes, nombre) values (729, 1977, 12, 'Zulauf and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (730, 1920, 4, 'Cormier Inc');
insert into revistas (id_revista, ano, mes, nombre) values (731, 2017, 8, 'Muller and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (732, 1974, 1, 'Paucek Inc');
insert into revistas (id_revista, ano, mes, nombre) values (733, 1933, 10, 'Osinski, Heidenreich and Nienow');
insert into revistas (id_revista, ano, mes, nombre) values (734, 1931, 8, 'Abernathy-Nienow');
insert into revistas (id_revista, ano, mes, nombre) values (735, 2020, 12, 'McLaughlin, Abernathy and Gutkowski');
insert into revistas (id_revista, ano, mes, nombre) values (736, 1982, 1, 'Wehner-Cormier');
insert into revistas (id_revista, ano, mes, nombre) values (737, 1942, 3, 'Ondricka Inc');
insert into revistas (id_revista, ano, mes, nombre) values (738, 1947, 3, 'Crist, Feeney and Renner');
insert into revistas (id_revista, ano, mes, nombre) values (739, 2009, 11, 'Waters, Thiel and Nienow');
insert into revistas (id_revista, ano, mes, nombre) values (740, 1962, 10, 'Rowe, Lubowitz and Gaylord');
insert into revistas (id_revista, ano, mes, nombre) values (741, 1992, 8, 'Dibbert-O''Reilly');
insert into revistas (id_revista, ano, mes, nombre) values (742, 1977, 7, 'Kreiger, Macejkovic and O''Kon');
insert into revistas (id_revista, ano, mes, nombre) values (743, 2013, 12, 'Nader Inc');
insert into revistas (id_revista, ano, mes, nombre) values (744, 1960, 2, 'Wyman and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (745, 2008, 6, 'Wilderman, McLaughlin and Wintheiser');
insert into revistas (id_revista, ano, mes, nombre) values (746, 2004, 8, 'Schaden, Little and Durgan');
insert into revistas (id_revista, ano, mes, nombre) values (747, 1992, 2, 'Bartoletti, Effertz and Hansen');
insert into revistas (id_revista, ano, mes, nombre) values (748, 2009, 10, 'Powlowski, Durgan and Sauer');
insert into revistas (id_revista, ano, mes, nombre) values (749, 1993, 7, 'Mertz-Dicki');
insert into revistas (id_revista, ano, mes, nombre) values (750, 1991, 6, 'Bauch Group');
insert into revistas (id_revista, ano, mes, nombre) values (751, 1963, 11, 'Hirthe LLC');
insert into revistas (id_revista, ano, mes, nombre) values (752, 2014, 9, 'Crooks-Lockman');
insert into revistas (id_revista, ano, mes, nombre) values (753, 1926, 4, 'Braun LLC');
insert into revistas (id_revista, ano, mes, nombre) values (754, 2019, 10, 'Block, Heathcote and Mertz');
insert into revistas (id_revista, ano, mes, nombre) values (755, 1930, 3, 'Harris LLC');
insert into revistas (id_revista, ano, mes, nombre) values (756, 1961, 12, 'McClure Group');
insert into revistas (id_revista, ano, mes, nombre) values (757, 1989, 11, 'Lowe, Walker and Kemmer');
insert into revistas (id_revista, ano, mes, nombre) values (758, 2023, 12, 'Gleichner and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (759, 2003, 1, 'Cremin, Kautzer and Hills');
insert into revistas (id_revista, ano, mes, nombre) values (760, 1956, 5, 'Hudson-Rau');
insert into revistas (id_revista, ano, mes, nombre) values (761, 2004, 6, 'Wyman, Hermiston and Dicki');
insert into revistas (id_revista, ano, mes, nombre) values (762, 1981, 5, 'Hammes Inc');
insert into revistas (id_revista, ano, mes, nombre) values (763, 1915, 3, 'Collins and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (764, 1994, 9, 'Morar and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (765, 1931, 2, 'Mueller, Swift and Paucek');
insert into revistas (id_revista, ano, mes, nombre) values (766, 1937, 11, 'Hane-Schumm');
insert into revistas (id_revista, ano, mes, nombre) values (767, 2017, 4, 'Gutkowski-Nolan');
insert into revistas (id_revista, ano, mes, nombre) values (768, 2023, 7, 'Langworth-Becker');
insert into revistas (id_revista, ano, mes, nombre) values (769, 1959, 4, 'Bogisich, Casper and Leffler');
insert into revistas (id_revista, ano, mes, nombre) values (770, 1928, 2, 'Gislason-Kuhn');
insert into revistas (id_revista, ano, mes, nombre) values (771, 1929, 6, 'Schiller Inc');
insert into revistas (id_revista, ano, mes, nombre) values (772, 1950, 11, 'Dibbert, Dach and Effertz');
insert into revistas (id_revista, ano, mes, nombre) values (773, 1934, 8, 'Runolfsdottir, Ledner and Hegmann');
insert into revistas (id_revista, ano, mes, nombre) values (774, 1956, 10, 'Raynor LLC');
insert into revistas (id_revista, ano, mes, nombre) values (775, 1946, 9, 'Hayes, Schultz and Dooley');
insert into revistas (id_revista, ano, mes, nombre) values (776, 1985, 7, 'Doyle and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (777, 1950, 10, 'Hilll Group');
insert into revistas (id_revista, ano, mes, nombre) values (778, 1949, 3, 'Cormier Group');
insert into revistas (id_revista, ano, mes, nombre) values (779, 2009, 9, 'Swaniawski-Heaney');
insert into revistas (id_revista, ano, mes, nombre) values (780, 1914, 1, 'Cronin and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (781, 1923, 7, 'Wisoky, Kuphal and Klein');
insert into revistas (id_revista, ano, mes, nombre) values (782, 1977, 10, 'Kutch Group');
insert into revistas (id_revista, ano, mes, nombre) values (783, 1997, 3, 'Bogan-Quigley');
insert into revistas (id_revista, ano, mes, nombre) values (784, 2010, 8, 'Pollich, Bogisich and Wilderman');
insert into revistas (id_revista, ano, mes, nombre) values (785, 1990, 4, 'Gusikowski, Pfannerstill and Kunze');
insert into revistas (id_revista, ano, mes, nombre) values (786, 1997, 12, 'Kunde Group');
insert into revistas (id_revista, ano, mes, nombre) values (787, 1977, 7, 'Fritsch-Tremblay');
insert into revistas (id_revista, ano, mes, nombre) values (788, 1969, 3, 'Yost, Schamberger and Baumbach');
insert into revistas (id_revista, ano, mes, nombre) values (789, 1973, 9, 'Bins Group');
insert into revistas (id_revista, ano, mes, nombre) values (790, 1966, 5, 'Ankunding, Sauer and Sauer');
insert into revistas (id_revista, ano, mes, nombre) values (791, 1988, 5, 'Morissette-Gibson');
insert into revistas (id_revista, ano, mes, nombre) values (792, 1995, 8, 'Lindgren and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (793, 1914, 3, 'Wiza, Wunsch and Goldner');
insert into revistas (id_revista, ano, mes, nombre) values (794, 2018, 10, 'Sauer, Simonis and Littel');
insert into revistas (id_revista, ano, mes, nombre) values (795, 1965, 1, 'Rogahn Inc');
insert into revistas (id_revista, ano, mes, nombre) values (796, 2022, 1, 'Jacobi Group');
insert into revistas (id_revista, ano, mes, nombre) values (797, 2014, 2, 'Kohler LLC');
insert into revistas (id_revista, ano, mes, nombre) values (798, 1932, 10, 'Lebsack and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (799, 1966, 5, 'Stanton-Graham');
insert into revistas (id_revista, ano, mes, nombre) values (800, 1925, 12, 'Jones Inc');
insert into revistas (id_revista, ano, mes, nombre) values (801, 1999, 11, 'Simonis LLC');
insert into revistas (id_revista, ano, mes, nombre) values (802, 1987, 6, 'Howell, Mitchell and Schulist');
insert into revistas (id_revista, ano, mes, nombre) values (803, 1991, 6, 'Torphy, Nikolaus and Brown');
insert into revistas (id_revista, ano, mes, nombre) values (804, 1915, 6, 'Lehner-Osinski');
insert into revistas (id_revista, ano, mes, nombre) values (805, 1990, 1, 'Ledner, Hermann and Shields');
insert into revistas (id_revista, ano, mes, nombre) values (806, 2018, 5, 'Lueilwitz Group');
insert into revistas (id_revista, ano, mes, nombre) values (807, 1981, 1, 'Hessel-Kozey');
insert into revistas (id_revista, ano, mes, nombre) values (808, 1915, 11, 'Ortiz LLC');
insert into revistas (id_revista, ano, mes, nombre) values (809, 1929, 12, 'Quitzon-Kozey');
insert into revistas (id_revista, ano, mes, nombre) values (810, 1947, 3, 'Hane-Prosacco');
insert into revistas (id_revista, ano, mes, nombre) values (811, 1975, 9, 'Rohan-Funk');
insert into revistas (id_revista, ano, mes, nombre) values (812, 1987, 6, 'Altenwerth Inc');
insert into revistas (id_revista, ano, mes, nombre) values (813, 1999, 8, 'Lowe, Connelly and Casper');
insert into revistas (id_revista, ano, mes, nombre) values (814, 1988, 6, 'Abbott, Buckridge and Bayer');
insert into revistas (id_revista, ano, mes, nombre) values (815, 1920, 10, 'McGlynn Inc');
insert into revistas (id_revista, ano, mes, nombre) values (816, 1922, 3, 'Deckow, Langosh and Stanton');
insert into revistas (id_revista, ano, mes, nombre) values (817, 2000, 10, 'Hamill and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (818, 1929, 12, 'Jenkins-Buckridge');
insert into revistas (id_revista, ano, mes, nombre) values (819, 1977, 7, 'Christiansen and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (820, 1955, 7, 'Reynolds Group');
insert into revistas (id_revista, ano, mes, nombre) values (821, 2021, 12, 'Hahn and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (822, 2018, 3, 'Blanda LLC');
insert into revistas (id_revista, ano, mes, nombre) values (823, 1939, 4, 'Schmitt LLC');
insert into revistas (id_revista, ano, mes, nombre) values (824, 1960, 11, 'Gaylord and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (825, 1944, 5, 'Russel-Abernathy');
insert into revistas (id_revista, ano, mes, nombre) values (826, 1917, 8, 'Ebert and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (827, 1997, 3, 'Stark, Klocko and Muller');
insert into revistas (id_revista, ano, mes, nombre) values (828, 2021, 3, 'Lockman, Macejkovic and Heller');
insert into revistas (id_revista, ano, mes, nombre) values (829, 2002, 4, 'Feeney, Langosh and Jacobs');
insert into revistas (id_revista, ano, mes, nombre) values (830, 1971, 11, 'Cruickshank, Gulgowski and Witting');
insert into revistas (id_revista, ano, mes, nombre) values (831, 1947, 3, 'Schumm and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (832, 2023, 9, 'Lakin, Moen and Nienow');
insert into revistas (id_revista, ano, mes, nombre) values (833, 1940, 4, 'Braun Inc');
insert into revistas (id_revista, ano, mes, nombre) values (834, 1962, 6, 'Fisher-Rosenbaum');
insert into revistas (id_revista, ano, mes, nombre) values (835, 1928, 10, 'Cronin, Barton and Emard');
insert into revistas (id_revista, ano, mes, nombre) values (836, 1952, 5, 'Stamm-Lind');
insert into revistas (id_revista, ano, mes, nombre) values (837, 1959, 12, 'Goodwin-Nolan');
insert into revistas (id_revista, ano, mes, nombre) values (838, 1969, 6, 'Bahringer, Reinger and Koch');
insert into revistas (id_revista, ano, mes, nombre) values (839, 1925, 11, 'Dicki Inc');
insert into revistas (id_revista, ano, mes, nombre) values (840, 1951, 8, 'Toy, Collins and Johnston');
insert into revistas (id_revista, ano, mes, nombre) values (841, 2017, 12, 'Conn, Kessler and Zieme');
insert into revistas (id_revista, ano, mes, nombre) values (842, 1992, 11, 'Ledner and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (843, 1932, 3, 'Grant-Kozey');
insert into revistas (id_revista, ano, mes, nombre) values (844, 2019, 7, 'Mitchell-Ferry');
insert into revistas (id_revista, ano, mes, nombre) values (845, 1927, 2, 'Marks-Kuhn');
insert into revistas (id_revista, ano, mes, nombre) values (846, 2013, 10, 'Connelly-Lowe');
insert into revistas (id_revista, ano, mes, nombre) values (847, 1991, 4, 'Leannon-Macejkovic');
insert into revistas (id_revista, ano, mes, nombre) values (848, 1943, 8, 'Blick, Homenick and Stracke');
insert into revistas (id_revista, ano, mes, nombre) values (849, 1935, 2, 'Johnston Inc');
insert into revistas (id_revista, ano, mes, nombre) values (850, 1980, 7, 'Bernier, Hagenes and Marquardt');
insert into revistas (id_revista, ano, mes, nombre) values (851, 2007, 8, 'Kemmer-O''Connell');
insert into revistas (id_revista, ano, mes, nombre) values (852, 1917, 3, 'Ward, Ratke and Lind');
insert into revistas (id_revista, ano, mes, nombre) values (853, 2014, 7, 'Mueller, Rempel and Bayer');
insert into revistas (id_revista, ano, mes, nombre) values (854, 2012, 9, 'Streich and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (855, 1983, 2, 'Denesik, Rodriguez and Kiehn');
insert into revistas (id_revista, ano, mes, nombre) values (856, 1990, 4, 'Collins Group');
insert into revistas (id_revista, ano, mes, nombre) values (857, 1988, 7, 'Pacocha, Konopelski and O''Keefe');
insert into revistas (id_revista, ano, mes, nombre) values (858, 1973, 4, 'Greenholt-Lakin');
insert into revistas (id_revista, ano, mes, nombre) values (859, 2015, 3, 'Gleichner and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (860, 1970, 5, 'Heidenreich-Corkery');
insert into revistas (id_revista, ano, mes, nombre) values (861, 1935, 8, 'Ritchie LLC');
insert into revistas (id_revista, ano, mes, nombre) values (862, 1966, 8, 'Hegmann and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (863, 1998, 6, 'Kuhlman LLC');
insert into revistas (id_revista, ano, mes, nombre) values (864, 2019, 5, 'Mante and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (865, 2003, 9, 'Swift Group');
insert into revistas (id_revista, ano, mes, nombre) values (866, 1944, 7, 'Schiller, McCullough and Hettinger');
insert into revistas (id_revista, ano, mes, nombre) values (867, 1960, 5, 'King-Wunsch');
insert into revistas (id_revista, ano, mes, nombre) values (868, 1931, 11, 'Lindgren, Torp and Stark');
insert into revistas (id_revista, ano, mes, nombre) values (869, 1937, 12, 'Bosco Group');
insert into revistas (id_revista, ano, mes, nombre) values (870, 1998, 12, 'Mitchell-Lesch');
insert into revistas (id_revista, ano, mes, nombre) values (871, 1921, 10, 'Jacobson Inc');
insert into revistas (id_revista, ano, mes, nombre) values (872, 1930, 12, 'Simonis and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (873, 1939, 5, 'Zboncak LLC');
insert into revistas (id_revista, ano, mes, nombre) values (874, 2015, 4, 'Ward, Witting and Grimes');
insert into revistas (id_revista, ano, mes, nombre) values (875, 1969, 3, 'Ernser, Grant and Casper');
insert into revistas (id_revista, ano, mes, nombre) values (876, 1954, 8, 'Goyette Group');
insert into revistas (id_revista, ano, mes, nombre) values (877, 1962, 5, 'Hayes Group');
insert into revistas (id_revista, ano, mes, nombre) values (878, 1942, 8, 'Gottlieb Group');
insert into revistas (id_revista, ano, mes, nombre) values (879, 1955, 8, 'Halvorson-Fadel');
insert into revistas (id_revista, ano, mes, nombre) values (880, 1919, 3, 'Cummings-Donnelly');
insert into revistas (id_revista, ano, mes, nombre) values (881, 1981, 3, 'Ondricka-Murray');
insert into revistas (id_revista, ano, mes, nombre) values (882, 1995, 12, 'Predovic-Stamm');
insert into revistas (id_revista, ano, mes, nombre) values (883, 1995, 1, 'Dickens, Tillman and McCullough');
insert into revistas (id_revista, ano, mes, nombre) values (884, 1976, 12, 'Bashirian-Grant');
insert into revistas (id_revista, ano, mes, nombre) values (885, 2021, 5, 'Maggio Group');
insert into revistas (id_revista, ano, mes, nombre) values (886, 1995, 5, 'Dach-Hoppe');
insert into revistas (id_revista, ano, mes, nombre) values (887, 1957, 5, 'Becker-Nolan');
insert into revistas (id_revista, ano, mes, nombre) values (888, 1973, 6, 'Kling, Kuhic and Jones');
insert into revistas (id_revista, ano, mes, nombre) values (889, 2003, 7, 'Hermiston Group');
insert into revistas (id_revista, ano, mes, nombre) values (890, 1992, 10, 'Wisoky, Rolfson and Cremin');
insert into revistas (id_revista, ano, mes, nombre) values (891, 1997, 1, 'Volkman, Parisian and McGlynn');
insert into revistas (id_revista, ano, mes, nombre) values (892, 1996, 5, 'Baumbach-Weissnat');
insert into revistas (id_revista, ano, mes, nombre) values (893, 1953, 11, 'Durgan LLC');
insert into revistas (id_revista, ano, mes, nombre) values (894, 2018, 12, 'Flatley and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (895, 1914, 2, 'Cormier-Padberg');
insert into revistas (id_revista, ano, mes, nombre) values (896, 1929, 8, 'Gerhold and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (897, 2001, 1, 'Wiegand LLC');
insert into revistas (id_revista, ano, mes, nombre) values (898, 1932, 5, 'Kohler-O''Hara');
insert into revistas (id_revista, ano, mes, nombre) values (899, 2001, 7, 'Considine and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (900, 1985, 12, 'Mohr Group');
insert into revistas (id_revista, ano, mes, nombre) values (901, 1992, 4, 'Runolfsson Group');
insert into revistas (id_revista, ano, mes, nombre) values (902, 1978, 10, 'Rice and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (903, 2023, 8, 'Simonis and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (904, 1939, 10, 'Walsh-Wintheiser');
insert into revistas (id_revista, ano, mes, nombre) values (905, 1954, 12, 'Muller, Orn and Robel');
insert into revistas (id_revista, ano, mes, nombre) values (906, 2017, 9, 'Roob-Beier');
insert into revistas (id_revista, ano, mes, nombre) values (907, 1931, 5, 'Satterfield LLC');
insert into revistas (id_revista, ano, mes, nombre) values (908, 1953, 9, 'Bashirian-Nolan');
insert into revistas (id_revista, ano, mes, nombre) values (909, 1992, 6, 'Ebert and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (910, 1959, 7, 'Mueller Group');
insert into revistas (id_revista, ano, mes, nombre) values (911, 1974, 1, 'Mills Group');
insert into revistas (id_revista, ano, mes, nombre) values (912, 1986, 2, 'Metz, Schaefer and Stracke');
insert into revistas (id_revista, ano, mes, nombre) values (913, 1953, 5, 'Sporer-Halvorson');
insert into revistas (id_revista, ano, mes, nombre) values (914, 2018, 4, 'Hane, Funk and Kutch');
insert into revistas (id_revista, ano, mes, nombre) values (915, 1989, 10, 'Gerlach, Krajcik and Goodwin');
insert into revistas (id_revista, ano, mes, nombre) values (916, 1977, 1, 'Dare-Harris');
insert into revistas (id_revista, ano, mes, nombre) values (917, 1918, 8, 'Klocko, Bogisich and Dietrich');
insert into revistas (id_revista, ano, mes, nombre) values (918, 1971, 1, 'Daniel Inc');
insert into revistas (id_revista, ano, mes, nombre) values (919, 1960, 3, 'Jacobs-Balistreri');
insert into revistas (id_revista, ano, mes, nombre) values (920, 1958, 3, 'Mueller-Parisian');
insert into revistas (id_revista, ano, mes, nombre) values (921, 1983, 12, 'Mueller-Corwin');
insert into revistas (id_revista, ano, mes, nombre) values (922, 2014, 8, 'Dicki, Tremblay and Kuhn');
insert into revistas (id_revista, ano, mes, nombre) values (923, 2008, 12, 'Moen LLC');
insert into revistas (id_revista, ano, mes, nombre) values (924, 1995, 4, 'Marks Group');
insert into revistas (id_revista, ano, mes, nombre) values (925, 1934, 8, 'Tremblay-Veum');
insert into revistas (id_revista, ano, mes, nombre) values (926, 2010, 12, 'Turcotte, Howell and Hodkiewicz');
insert into revistas (id_revista, ano, mes, nombre) values (927, 2022, 10, 'Schimmel, Ryan and Hammes');
insert into revistas (id_revista, ano, mes, nombre) values (928, 1930, 8, 'Purdy-Balistreri');
insert into revistas (id_revista, ano, mes, nombre) values (929, 2015, 6, 'Wisozk Group');
insert into revistas (id_revista, ano, mes, nombre) values (930, 1930, 9, 'Lubowitz and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (931, 1999, 9, 'Schroeder LLC');
insert into revistas (id_revista, ano, mes, nombre) values (932, 1922, 11, 'Powlowski, Wolf and Lockman');
insert into revistas (id_revista, ano, mes, nombre) values (933, 1939, 4, 'Lehner, Nader and Rohan');
insert into revistas (id_revista, ano, mes, nombre) values (934, 1944, 4, 'Osinski, Mante and Christiansen');
insert into revistas (id_revista, ano, mes, nombre) values (935, 1962, 12, 'Rohan LLC');
insert into revistas (id_revista, ano, mes, nombre) values (936, 2015, 4, 'Cremin-Simonis');
insert into revistas (id_revista, ano, mes, nombre) values (937, 1995, 10, 'Quitzon, Hilpert and Homenick');
insert into revistas (id_revista, ano, mes, nombre) values (938, 2021, 2, 'Lemke, Paucek and Kulas');
insert into revistas (id_revista, ano, mes, nombre) values (939, 1964, 1, 'Emard-Spencer');
insert into revistas (id_revista, ano, mes, nombre) values (940, 1921, 5, 'Deckow and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (941, 1921, 5, 'Abshire LLC');
insert into revistas (id_revista, ano, mes, nombre) values (942, 1937, 11, 'Nicolas-Friesen');
insert into revistas (id_revista, ano, mes, nombre) values (943, 1959, 6, 'Ortiz and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (944, 1927, 6, 'Berge, Torp and Ankunding');
insert into revistas (id_revista, ano, mes, nombre) values (945, 1980, 6, 'Baumbach LLC');
insert into revistas (id_revista, ano, mes, nombre) values (946, 1966, 7, 'Greenfelder-Osinski');
insert into revistas (id_revista, ano, mes, nombre) values (947, 2022, 6, 'McCullough, Mraz and Mohr');
insert into revistas (id_revista, ano, mes, nombre) values (948, 1926, 10, 'Gislason, Funk and Johns');
insert into revistas (id_revista, ano, mes, nombre) values (949, 1970, 1, 'Borer, Turcotte and Schamberger');
insert into revistas (id_revista, ano, mes, nombre) values (950, 2012, 7, 'Dicki-Mills');
insert into revistas (id_revista, ano, mes, nombre) values (951, 2015, 5, 'Lang-Hessel');
insert into revistas (id_revista, ano, mes, nombre) values (952, 1971, 8, 'Bosco, Cremin and Mante');
insert into revistas (id_revista, ano, mes, nombre) values (953, 1934, 1, 'Braun-Kirlin');
insert into revistas (id_revista, ano, mes, nombre) values (954, 1998, 7, 'Renner, Wolf and Gulgowski');
insert into revistas (id_revista, ano, mes, nombre) values (955, 1940, 2, 'Boyer and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (956, 2023, 6, 'Goodwin, Kuphal and VonRueden');
insert into revistas (id_revista, ano, mes, nombre) values (957, 2019, 9, 'Lueilwitz, Skiles and Macejkovic');
insert into revistas (id_revista, ano, mes, nombre) values (958, 1976, 1, 'Fahey, VonRueden and Goldner');
insert into revistas (id_revista, ano, mes, nombre) values (959, 1997, 9, 'Smith, Schuppe and Cartwright');
insert into revistas (id_revista, ano, mes, nombre) values (960, 1982, 9, 'Von Group');
insert into revistas (id_revista, ano, mes, nombre) values (961, 1970, 10, 'Huels-Schulist');
insert into revistas (id_revista, ano, mes, nombre) values (962, 1983, 2, 'Cartwright-Stracke');
insert into revistas (id_revista, ano, mes, nombre) values (963, 1945, 11, 'Nader-Witting');
insert into revistas (id_revista, ano, mes, nombre) values (964, 1938, 3, 'Barrows Group');
insert into revistas (id_revista, ano, mes, nombre) values (965, 1958, 3, 'Hessel, Quitzon and Willms');
insert into revistas (id_revista, ano, mes, nombre) values (966, 1996, 5, 'Murray Group');
insert into revistas (id_revista, ano, mes, nombre) values (967, 1953, 7, 'O''Kon-O''Connell');
insert into revistas (id_revista, ano, mes, nombre) values (968, 2007, 8, 'Wehner, Rau and Shanahan');
insert into revistas (id_revista, ano, mes, nombre) values (969, 1945, 8, 'Pouros-Dickinson');
insert into revistas (id_revista, ano, mes, nombre) values (970, 1914, 8, 'Heller, Schamberger and Orn');
insert into revistas (id_revista, ano, mes, nombre) values (971, 1929, 11, 'Ullrich, Steuber and Pollich');
insert into revistas (id_revista, ano, mes, nombre) values (972, 1932, 1, 'Jerde, Ziemann and DuBuque');
insert into revistas (id_revista, ano, mes, nombre) values (973, 1977, 3, 'Hoeger, Windler and Renner');
insert into revistas (id_revista, ano, mes, nombre) values (974, 1938, 12, 'Baumbach-Kertzmann');
insert into revistas (id_revista, ano, mes, nombre) values (975, 2004, 8, 'Kulas-Donnelly');
insert into revistas (id_revista, ano, mes, nombre) values (976, 1988, 6, 'Murphy and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (977, 1941, 12, 'Senger, Oberbrunner and Mohr');
insert into revistas (id_revista, ano, mes, nombre) values (978, 2012, 12, 'Hammes LLC');
insert into revistas (id_revista, ano, mes, nombre) values (979, 1991, 8, 'Sawayn-Heathcote');
insert into revistas (id_revista, ano, mes, nombre) values (980, 1954, 10, 'Mills LLC');
insert into revistas (id_revista, ano, mes, nombre) values (981, 1992, 1, 'Volkman, Renner and Padberg');
insert into revistas (id_revista, ano, mes, nombre) values (982, 1979, 11, 'Schaefer, Nolan and Reichel');
insert into revistas (id_revista, ano, mes, nombre) values (983, 1930, 9, 'Flatley Group');
insert into revistas (id_revista, ano, mes, nombre) values (984, 1973, 10, 'Goodwin, Dach and Wisoky');
insert into revistas (id_revista, ano, mes, nombre) values (985, 2010, 1, 'Pagac-Volkman');
insert into revistas (id_revista, ano, mes, nombre) values (986, 1958, 12, 'Funk LLC');
insert into revistas (id_revista, ano, mes, nombre) values (987, 1935, 2, 'Corkery and Sons');
insert into revistas (id_revista, ano, mes, nombre) values (988, 1988, 12, 'Wilkinson-Franecki');
insert into revistas (id_revista, ano, mes, nombre) values (989, 1996, 10, 'Beer, Cummerata and Torphy');
insert into revistas (id_revista, ano, mes, nombre) values (990, 1960, 10, 'Jakubowski, Lynch and Paucek');
insert into revistas (id_revista, ano, mes, nombre) values (991, 1952, 10, 'Grimes, Heaney and Bins');
insert into revistas (id_revista, ano, mes, nombre) values (992, 1936, 6, 'Bailey, McKenzie and Goldner');
insert into revistas (id_revista, ano, mes, nombre) values (993, 1959, 3, 'Lind-Hegmann');
insert into revistas (id_revista, ano, mes, nombre) values (994, 1915, 9, 'Bayer-Bins');
insert into revistas (id_revista, ano, mes, nombre) values (995, 2000, 11, 'Cassin, Gleichner and Rodriguez');
insert into revistas (id_revista, ano, mes, nombre) values (996, 1992, 3, 'Erdman-Mohr');
insert into revistas (id_revista, ano, mes, nombre) values (997, 1938, 3, 'Davis-Runte');
insert into revistas (id_revista, ano, mes, nombre) values (998, 2000, 10, 'Powlowski-Koch');
insert into revistas (id_revista, ano, mes, nombre) values (999, 1939, 2, 'Rohan, Koch and Johnston');
insert into revistas (id_revista, ano, mes, nombre) values (1000, 2018, 11, 'Bartoletti-Welch');
